### ISSUE TITLE
Google analytics reports

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#104]
Audience Overview reports:  Please include tracking of geolocations - user locations, sector, etc.  Looking for more information on who the users are.  Unclear what options are available, so please let me know what we can track.

Also, the Top Events report includes a "time change" layer - not sure what this is, but should be excluded from the list.  Also don't want to track virtual buoys.  Pls exclude those from the reports.

**Comment by kbailey-noaa** [comment]
Would like to make this high priority so Sept report reflects changes.

**Comment by gitchrisadams** [comment]
@kbailey-noaa and @Bobfrat I changed the monthly email to exclude "time change" and Virtual buoys for the top events report. Next months report should be all set for this.
As for Audience Overview report. That is not a custom report it is a default Report. So you can not edit how that report gets sent. What I could do though, is add geo location to that email that gets sent out. Looking at the settings I could include by country, by state, metro, and/or city.

**Comment by kbailey-noaa** [comment]
@gitchrisadams Do you mean include a separate report for tracking geolocation?  Would it break down the # users found in the audience overview report by location?

**Comment by gitchrisadams** [comment]
@kbailey-noaa  @Bobfrat Yes, it would be a separate report in the same email.  Yes it would break down the users found in audience overview by location. I could send you a sample one time email of the report if you would like? Just let me know.

**Comment by kbailey-noaa** [comment]
@gitchrisadams Awesome.  Yes, pls send a sample to kathleen.bailey@noaa.gov.

**Comment by gitchrisadams** [comment]
@kbailey-noaa I just sent one by city and one by state. Each report could be included in the same email that goes out each month. Just let me know. 
Chris

**Comment by gitchrisadams** [comment]
@kbailey-noaa I added by City and by state to the monthly report, so next month will include that. If you would like us to send a one time report for city and state tomorrow, let us know. Unfortunately with the report I just can't send it, I have to schedule it for a day out.

**Comment by kbailey-noaa** [comment]
@gitchrisadams Sounds good re: _city and _state reports.  
Would you be able to provide the September reports (9/1 - 9/30) for the Location_state and Location_city, or is it too late?  If so, not a big deal.

**Comment by gitchrisadams** [comment]
@kbailey-noaa I just emailed you both reports.
