### ISSUE TITLE
Add NWPS layers - East Coast

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#105]
Add the NWPS as layers, around the US:
http://polar.ncep.noaa.gov/nwps/viewer.shtml

**Comment by Bobfrat** [comment]
@kbailey-noaa Right now we're harvesting and displaying layers for Wave Height, Period, and Direction and Wind Speed/Direction for Tampa Bay and Wakefield WFO's. So you want to add these 5 layers for each of the NWPS regions?

![screen shot 2017-09-04 at 2 46 30 pm](https://user-images.githubusercontent.com/5702672/30036293-dbc20a62-917f-11e7-9268-596b6e0f8a46.png)

**Comment by kbailey-noaa** [comment]
Yes please.

**Comment by kbailey-noaa** [comment]
Start with these layers:
- [ ] WFO Mt. Holly, Philadelphia
- [ ] WFO New York, New York
- [ ] WFO Jacksonville, FL
