### ISSUE TITLE
NGOFS/NEGOFS/NWGOFS issues

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#107]
The NOAA Gulf OFS layers are missing subdomains.
Looking at currents layers:

In NGOFS (see https://tidesandcurrents.noaa.gov/ofs/ngofs/ngofs.html) the blue markers are subdomains.  In EDS several subdomains are missing from the NGOFS layer.  (Note that NGOFS is a lower resolution version of NEGOFS/NWGOFS). Matagorda, Sabine Neches, Calcasieu - Lake Charles, maybe a piece of Gulfport just north of Deer Island going into Back Bay of Biloxi?, Pascagoula, and Galveston going into Houston Ship Channel).  The domain appears to be getting cut off?

NWGOFS and NEGOFS - even more subdomains' areas are missing - entirety of Galveston Bay, Lake Charles, etc.

Here is a comparison of NWGOFS layers shown in EDS vs CO-OPS. Note the currents don't extend all teh way into Matagorda Bay:
![matagorda_nwgofs_eds](https://user-images.githubusercontent.com/11823385/31234580-4672d2ec-a9bd-11e7-907e-ca3aebea85cd.PNG)
![matagorda_nwgofs_co-ops](https://user-images.githubusercontent.com/11823385/31234581-4673486c-a9bd-11e7-9871-a815607bf761.PNG)

**Comment by kknee** [comment]
@kbailey-noaa taking a closer look today.

**Comment by kbailey-noaa** [comment]
@kknee Moved this to Milestone 1.2.3 but unclear if this is high or low effort.  If low, might be worth moving to 1.2.2.

**Comment by kbailey-noaa** [comment]
This was resolved.
