### ISSUE TITLE
CNAPS model

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#109]
For consideration/discussion:
Add CNAPS variables:
https://data.ioos.us/dataset/coupled-northwest-atlantic-prediction-system-cnaps

Adding this to the queue but want to make sure we're not embarking on a huge level of effort, considering the addition of other RA models.  

Label as a SECOORA layer.

**Comment by kbailey-noaa** [comment]
http://omgsrv1.meas.ncsu.edu:8080/CNAPS/atm.jsp#

**Comment by kknee** [comment]
Specifically add waves, wind speed, water temp, salinity

**Comment by kbailey-noaa** [comment]
Per 6/15/18 call:  Currents might be already in EDS (@kknee will check/confirm) - I will create a new issue just for currents and tag as Release 1.2.2.  Keeping this issue open and written as is (which specifies waves/winds/water temp/salinity) but tagged it with a later milestone.  Still a priority considering NOS funding RPS/NCSU to get CNAPS into the cloud - we want to ensure it's available on EDS too.

**Comment by kknee** [comment]
CNAPS winds task moved to #165
