### ISSUE TITLE
Reorganize EDS Viewer table of contents

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#110]
As the layer list grows longer, will need to consider how to reorganize the TOC to be more user-friendly.  
- [x]  Introduce collapsible functionality
- [x]  Organize layers by region, rather than by variable.  (Global, National, Great Lakes, East Coast, Gulf Coast, Caribbean, West Coast, Alaska, Pacific)
- [x] rename observation layers
- [x] reorg HFR layers

**Comment by kbailey-noaa** [comment]
To elaborate, something like this, but I'm open to suggestion, esp if you've already developed something:

+**East Coast** --> Collapsible
- CBOFS 
   +Variable list --> Collapsible?
- DBOFS
   +Variable list

**Comment by kbailey-noaa** [comment]
"Observations" reorg:  Received feedback from RAs that organizing by owner/program doesn't make sense (e.g. CDIP) and is misleading.  Therefore, renaming obs layers as variable/observing environment rather than data source/owner solves some concerns about attribution - NDBC and CDIP layers include RA stations, so renaming as 'wave buoys' or 'marine weather' omits any implication of ownership.

CDIP = **Wave buoys**
CO-OPS = **Water level/meteorological stations**
NERRS = **Estuarine stations**
Maryland DNR = **Maryland tidewater ecosystem stations**
NDBC & Partner Stations = **Marine weather buoys/stations**
NDBC Partner Profiling Stations = **Current profiling stations**
Bundle HF Radar stations as:

+**Surface Currents** --> Collapsible
+ IOOS East/Gulf Coast HF Radar
+ -IOOS HF Radar --> Collapsible
 -- 1km
 -- 2km
 -- 6km
IOOS Hawaii HF Radar (6km)
...etc

**Comment by kknee** [comment]
@kbailey-noaa made a ton of changes to fix names etc last week, doing a final check/test today

**Comment by kbailey-noaa** [comment]
@kknee I see in dev - looks great.  Could you order the layer names within each region alphabetically?  Or at least keep the owners listed together? 

Also, can you reorder the TOC section headers as:
Observations
East Coast
Great Lakes
Gulf of Mexico
Caribbean
Pacific
Alaska
Global 
CONUS
Other
Channels
In Development

I combed through the dev layer names - here are some things I found:

Observations:

- The HF Radar name changes described in issue #111 reverted back - "IOOS" is missing from those HFR layers.  If all the things in dev are moved to production I didn't want to lose that.

East Coast: 

- There are 2 "IOOS STPS Currents" layers in the the East Coast region but one is actually a west coast domain.

Pacific: 

- PacIOOS (Mariana WW3 Height) is the only layer with parentheses.
- PacIOOS ROMS **Western Northern** Pacific should be Western **North** Pacific.
- "ROMS" is missing from the SCCOOS/CeNCOOS water temp layer name.

Caribbean:

- Remove "CARIB" from the CARICOOS layers.

Global:

- There are PacIOOS Samoa layers there that should be in the Pacific region. 
- I think you can remove "global" from the 2 NOAA Global RTOFS Currents names, since it's already in the global section.

Other:

- The PacIOOS and MARACOOS layers should be relocated to Pacific and East Coast regions, respectively.  (I actually couldn't' get MARACOOS East Coast (PE Shelf) to load).

In Development:
- CIOFS layers wouldn't load (but names etc look good).

**Comment by kknee** [comment]
thanks @kbailey-noaa  and apologies - I didn't mean that you should test, just that we made a ton of changes that needed to be tested internally

**Comment by kknee** [comment]
@kbailey-noaa took care of most of the above, couple notes:

Observations - the requested names in #111 don't actually have the term HFRADAR in the tile, should they?

STPS - the smaller domains include mention of geography in the title, e.g. IOOS Hawaii STPS Currents - should we do this for east and west coast to be consistent?

MARACOOS East Coast (PE Shelf) was removed - it's an extremely unreliable source

CIOFS see my comments in that issue

**Comment by kbailey-noaa** [comment]
Please make these name changes:
- [ ] IOOS National HF Radar 1 km
- [ ] IOOS National HF Radar 2 km
- [ ] IOOS National HF Radar 6 km
- [ ] IOOS East/Gulf Coast (USEGC) HF Radar x km
- [ ] IOOS Hawaii (USHI) HF Radar x km
- [ ] IOOS Puerto Rico/VI (PRVI) HF Radar x km
- [ ] IOOS West Coast (USWC) HF Radar x km

- [ ] MARACOOS STPS currents (6 or 8?) km
- [ ] IOOS STPS currents --> @kknee Is this the MAB 6 km layer in http://nopp.dms.uconn.edu:8080/thredds/catalog.html?  If my assumption is correct, then rename to **IOOS MAB STPS currents 6 km**
- [ ] IOOS West Coast STPS currents 6 km 
- [ ] IOOS Hawaii STPS currents 6 km 

- [ ] NOAA LEOFS Water Temperature (there was a typo)

**Comment by Bobfrat** [comment]
No problem EDS team plan to make these updates on Monday

**Comment by Bobfrat** [comment]
@kbailey-noaa layer names have been updated. I did notice a couple layers that seem inconsistent now.

Florida (STPS) and MARACOOS Mid Atlantic HF Radar

**Comment by kbailey-noaa** [comment]
@Bobfrat MARACOOS mid atlantic HFR is ok - this differentiates the MARACOOS product from the IOOS HFR products.  

Good catch - pls change Florida (STPS) to **IOOS Florida STPS Currents 6 km**.

**Comment by kbailey-noaa** [comment]
@Bobfrat what about the MARACOOS Mid Atlantic HFR layer?

**Comment by Bobfrat** [comment]
Whoops i spaced on that, should be coming through soon.

**Comment by kbailey-noaa** [comment]
Thanks! I see it now.
