### ISSUE TITLE
DBOFS currents island shows vectors

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#112]
For DBOFS Currents layer - One of the islands on the Delaware River right outside Philadelphia shows current vectors running over it.  The other islands are ok - vectors run around the landmass.  Unclear if this is an issue with CO-OPS data or with EDS visualization.  Can you please confirm/fix?

![dbofs_island](https://user-images.githubusercontent.com/11823385/34441223-50790c3a-ec88-11e7-852f-b02ff256a446.PNG)

**Comment by brianmckenna** [comment]
@kbailey-noaa took a quick look at [CO-OPS DBOFS Agg](https://opendap.co-ops.nos.noaa.gov/thredds/dodsC/DBOFS/fmrc/Aggregated_7_day_DBOFS_Fields_Forecast_best.ncd.html) and looks like this island is not masked in the model.

green is water, yellow is masked land values, for reference, the view includes two islands that are masked down near airport.
![dbofs_mask](https://user-images.githubusercontent.com/207820/34442123-1a066890-ec8e-11e7-988f-8f25d98ad4c1.png)

Something seems odd with the bathymetry regardless of mask, actually gets deeper (~-4m) where edges of island are the min depth of -2.5m. red is the main channel north and the smaller channel south of island
(_same plot, two different zooms_)
![dbofs_bathy_zoom](https://user-images.githubusercontent.com/207820/34442199-8ce6d5b6-ec8e-11e7-88b4-7d68ffce53e0.png)
![dbofs_bathy](https://user-images.githubusercontent.com/207820/34442204-9375662c-ec8e-11e7-8479-fb9662161150.png)

checked masks on u/v grids as well, same, showing rho to go along with bathy.

**Comment by kbailey-noaa** [comment]
@brianmckenna - Thanks!  I will pass this along to CO-OPS.  Very strange.  If you don't mind, I'll cc you in case they have questions about this analysis (though seems pretty straightforward).
