### ISSUE TITLE
WW3 height 

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#114]
I'm trying to look at WW3 height (global) zoomed in on the east coast during the bomb cyclone.  Finding the color ramp to be limiting - there is not enough granularity to really see the 'eye' of the cyclone.  Also the legend shows a max value of 7.88 m but dropping a virtual buoy shows higher wave heights (12 m).  
Ideally we'd see a clearer image like this: http://polar.ncep.noaa.gov/waves/viewer.shtml?-multi_1-US_eastcoast-

**Comment by Bobfrat** [comment]
@kbailey-noaa we'll need to set a higher max for the wave height layer scale. You can adjust the scale by clicking on the layer settings icon in the TOC, but only between 0-7 meters. We're currently working on improving the ability to customize the WMS layer settings. 

![screen shot 2018-01-04 at 11 31 23 am](https://user-images.githubusercontent.com/5702672/34573659-de724880-f142-11e7-9842-f45d45c87aea.png)

**Comment by kbailey-noaa** [comment]
I see it! Looks good.  Thanks.
