### ISSUE TITLE
Espresso roms 

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#115]
Espresso ROMS currents layer shows data but when I drop a virtual buoy I get 'no results.'
Tried in dev version of oceansmap and it worked fine.

**Comment by kknee** [comment]
working fine for me on production, can you post a screeenshot

![image](https://user-images.githubusercontent.com/196868/34608517-ad4cf580-f1e6-11e7-98ba-99ece057fd89.png)

**Comment by kbailey-noaa** [comment]
Works for me now too.  Weird...  Closing this.
