### ISSUE TITLE
LHazard request: labels/HFR layer addition

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#119]
From Lisa Hazard:
Just wanted to follow up on this email chain again.  This is minor, but I do believe that keeping naming conventions consistent leads to reduced confusion.

Change Request:
1.) Under "Currents" -> change "West Coast (STPS, USWC) to "STPS_WESTCOAST" 
This is the same as all the other STPS "regions" (e.g. STPS_FLORIDA, STPS_HAWAII, STPS_MAB...)

2.) Under "Currents" -> add "STPS_GULFCOAST" - to my knowledge there is a product there that is not represented.

3.) Under "Currents" -> identify what "West Coast (CA 3km)" is....  Is that the ROMS model??

4.) As best I can tell, Under "Currents" -> IOOS HF Radar 1km, 2km, 6km, it has all of the regions on there including Hawaii and Puerto Rico/Virgin Islands.
Recommend including boxes around those regions as well and then removing the individual lines for "IOOS Hawaii HF Radar (6km), IOOS Puerto Rico/Virgin Islands HF Radar (6km), IOOS West Coast HF Radar (6km) as the data is already there.

5.) Under "Currents" -> add IOOS HF Radar 500m San Francisco bay has 500meter currents....

**Comment by kknee** [comment]
@kbailey-noaa 

1) - can we go the other way to be consistent with our naming conventions of geography or RA first, then dataset name - e.g. Hawaii (STPS)?

2) - we don't current collect STPS for the Gulf coast with EDS.  We can, but probably not in time for May 3 with all the other data integration happening

3)  Yes this is ROMS, jointly funded by CENCOOS and SCCOOS - so 'West Coast (ROMS)' ?

4) Let's talk about this one - this is a tile service vs. WMS issue - there are pros and cons to both which is why we have both.  The ones that Lisa wants us to keep are the tile services, but we can't query data from those.

5) Ok, this is another dataset that EDS does not currently collect, so might need to push out the milestone to get this in

**Comment by kknee** [comment]
@kbailey-noaa poking around in here, I think I found the 500 m SanFran source: http://hfrnet-tds.ucsd.edu/thredds/catalog/HFR/USWC/500m/hourly/RTV/catalog.html

Let me know if that is not correct.

**Comment by kbailey-noaa** [comment]
@kknee Thanks! 
Re: 1 - 3: I agree with all.  Can defer STPS to the next release. 
For 4 I didn't even realize the IOOS x km layers were a tile service!  I definitely don't want to get rid of the individual lines (PR, HI, etc).  I'm wondering why we don't use WMS for the larger layers?  The abstract doesn't show the data source for those layers either.  Keep as is but we do need to update the abstract with data sources.
For 5 (500 m san fran), I confirmed the source with Lisa (as you probably saw).  It's definitely lower priority than the other things listed in the May 3 release, so we can defer that to the next release if it's too time consuming.  I don't want to push the May 3 date back though, if possible.

**Comment by kknee** [comment]
@kbailey-noaa for No. 4 - we have gone back and forth on what to include tile/wms, resolution, etc.

Right now we show tiles for all resolutions and EDS WMS for the 6km (EDS only collects 6km).

For the tile service source, do you want us to point back to the HFRDAC TDS?  Or the tile service URL?

**Comment by kknee** [comment]
@kbailey-noaa is there a reason that the Alaska sources are not included in Lisa's request?  Poking around, I see both HFR and STPS available

**Comment by kbailey-noaa** [comment]
@kknee Nope, but it would be great to start including Alaska sources.  We don't have a whole lot up there.

**Comment by kbailey-noaa** [comment]
Per our call 6/15/18: Decided to split out the new data source requests into a new issue, and will close this out since the layer names were updated.
