### ISSUE TITLE
Replace ESPRESSO with DOPPIO

### ISSUE THREAD

**Issue by kknee** [asascience-open/IOOS-EDS#120]

**Comment by kknee** [comment]
Doppio is now available on EDS, next step is to have John Wilkin review

**Comment by kbailey-noaa** [comment]
Is this ready for release 1.2.2?

**Comment by kbailey-noaa** [comment]
Per our call 6/15/18, this is ready to go.

**Comment by kknee** [comment]
@kbailey-noaa these on on the dev OM site.  You can check them out, but we need to add the parameter name to the layer name before release.

**Comment by kbailey-noaa** [comment]
They look great!

**Comment by kknee** [comment]
@kbailey-noaa names have been updated this is all set

**Comment by kbailey-noaa** [comment]
@kknee I saw one espresso layer still in dev - is that going away?  I don't know the background so not sure if they are getting entirely replaced by doppio or not..

**Comment by kbailey-noaa** [comment]
@kknee Yes, please ask MARACOOS.  If they don't want it running we should remove it.

**Comment by kbailey-noaa** [comment]
@kknee This is low priority but also seems like low effort.  Your choice whether to keep it in milestone 2.0.1 or move to 2.1.

**Comment by kknee** [comment]
@kbailey-noaa they would like to keep it in, so I think we can close this?

**Comment by kbailey-noaa** [comment]
Yep, resolved.  Thanks!
