### ISSUE TITLE
THREDDS cleanup

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#122]
For some reason I thought we had this issue in but I can't find it.  A while ago we discussed cleaning up the THREDDS catalog - this was pertinent to meeting OR&R's needs.  

A note from Derrick that puts this request into perspective:
"I recommend we think of the EDS THREDDS as our IOOS best practice. Which to me means aggregating for all data sets. Standards compliant for all grid types. Complete up to date metadata with attribution. Registration in the catalog etc. If after doing the best we can, they (OR&R) still need added features then using the API is fine. I just feel like EDS is a flagship product and it should be an exemplar data service. Best in class for the RAs.
Thinking about an outline...
1. Why do we need this reference
2. Examples of well organized THREDDS catalogs
    2.1 By region
    2.2 By feature type
3. Links to references to implement the Best Practices in 2"

**Comment by kknee** [comment]
@kbailey-noaa totally agree.  we are working towards this goal -already had it in mind based on previous discussions.  It is a fairly large effort.

**Comment by kbailey-noaa** [comment]
Given major THREDDS improvements, closing this out.  We are now soliciting user feedback on their metadata, which might require minor changes.
