### ISSUE TITLE
Add CIOFS

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#123]
https://opendap.co-ops.nos.noaa.gov/thredds/ciofs_catalog.html

Include "development" in label or as part of TOC header.

**Comment by kknee** [comment]
@kbailey-noaa what do you want to use for an abstract?  

Name should be 'NOAA Cook Inlet (CIOFS)' in line with the others?

**Comment by kbailey-noaa** [comment]
@kknee This note is to document what we discussed on our call: CIOFS is highest priority since CO-OPS and users are asking for it.  We decided to roll out variables as they are ready (e.g. currents).  Water temp data might have issues related to masking. AJ is a resource if you have questions.

**Comment by kknee** [comment]
@kbailey-noaa all five variables on on the dev OM site for you to check out.  Currents are ready to go.  I don't think you want winds right (we don't include for other OFS models).  SST, water level, and salinity need a little more work.

**Comment by kknee** [comment]
@kbailey-noaa they are in the new 'In Development' category.

**Comment by kbailey-noaa** [comment]
@kknee Looks good. I see what you mean about the SST/WL/Salinity but they look a lot better than Friday.  I recommend keeping the winds just because we're designing this release of layers for CO-OPS testers who likely want to see the winds along with the other layers in one place.  Later, once CIOFS goes live, we would remove them since the winds are already available as a broader layer.

**Comment by kbailey-noaa** [comment]
@kknee I wasn't able to use the drop a virtual buoy feature, FYI.

**Comment by kknee** [comment]
@kbailey-noaa CIOFS has not been posted reliably for the last few weeks and we're also seeing a gap in the forecast.  lots of wrangling to get past these issues, we'll have it up on Monday for Tuesday's demo but after that we should talk about whether to keep it up in the current state

**Comment by kbailey-noaa** [comment]
I just talked to Pat about this. There are issues with the dev computer at NCEP that we won’t see once it’s moved to the production computer. I guess NCEP keeps stopping the runs to post updates to that computer plus other higher priority dev testing in the NWS. We should talk about this at the demo so AJ is aware and can communicate any outages to RPS for these dev layers. I didn’t realize their dev computer messed with the OFS runs so this was news to me.

**Comment by kbailey-noaa** [comment]
@kknee Once the abstract is added (see 6/13 comment) then I'll close this.  The layers look good.

**Comment by Bobfrat** [comment]
@kbailey-noaa abstract has been updated

**Comment by kbailey-noaa** [comment]
@Bobfrat I realize there are some issues with CIOFS, per Kelly's comment.  Is it possible to see if we can get any data in the Viewer for CO-OPS OFS users to test?  I was able to get 1 day of data on July 15 and July 22.  It's a little confusing though - I turned on salinity and currents and when I moved the slider to July 29 I realized the Valid time in the TOC says July 29 for currents and July 22 for Salinity but no data in the time-series plot...  Some of this might be resolved with the other timestamp issues in Release 2.0.1, though...
Looks like there are data available in their THREDDS. 

![ciofs](https://user-images.githubusercontent.com/11823385/43650976-279e743a-970f-11e8-93da-12d9c7aa5851.PNG)

**Comment by kknee** [comment]
@kbailey-noaa we can manually push data into the production EDS anytime, but I'd like to avoid asking the EDS team to do that everyday.   Do you have a timeframe you want us to push?  On the subject of automated harvesting - worth talking to CO-OPS about whether there is a forecast cycle that is available most reliably?

**Comment by kbailey-noaa** [comment]
@kknee understood.  I don't have a timeframe - any time period works as long as it's 3 consecutive days.  Can you reach out to AJ re: automated harvesting? I'm a little confused about all this, so not sure I'd ask the right questions.  I see the data are updating on their products (https://tidesandcurrents.noaa.gov/ofs/dev/ciofs/ciofs.html) so maybe they're posting again?  I'm not clear on why CO-OPS can display the data but we can't?  I assume this has something to do with how the data are processed?

**Comment by kbailey-noaa** [comment]
@Bobfrat @kknee  I'm confused about why CO-OPS can display the CIOFS data but the model viewer can't?  
https://tidesandcurrents.noaa.gov/ofs/dev/ofs_animation.shtml?ofsregion=ci&subdomain=0&model_type=wtemp_forecast
Is this a matter of harvest cycle timing - e.g. when EDS harvests from the [CO-OPS THREDDS](https://opendap.co-ops.nos.noaa.gov/thredds/catalog/NOAA/CIOFS/MODELS/201808/catalog.html) vs when the files are actually posted? I'm also assuming those netCDF files are the source of the CO-OPS displays..  I ask because I'm anticipating questions from users/modelers about this.

**Comment by kknee** [comment]
@kbailey-noaa I'm not sure what CO-OPS is doing on their end, they may have custom code to display whatever happens to be available.  The EDS is setup to collect the same forecast cycle at the same time everyday, so when there is inconsistently in in what results are available and when it causes issues.  The them is working harvesting two different cycles (so that we're harvesting 2x/day instead of one).

**Comment by kknee** [comment]
@kbailey-noaa fyi - we're collecting 3D forecasts (e.g. from https://opendap.co-ops.nos.noaa.gov/thredds/catalog/NOAA/CIOFS/MODELS/201808/catalog.html >> these files >> nos.ciofs.fields.f048.20180822.t06z.nc).

Looks like CO-OPS is showing 2D output, but I can't tell for sure.  I haven't been monitoring the stability of the 2D forecasts.

**Comment by kbailey-noaa** [comment]
@kknee I'm fairly sure CO-OPS is showing 2D, so that explains it...  Maybe we need to switch to harvesting 2D instead.  Is that a heavy lift?

**Comment by kbailey-noaa** [comment]
@kknee That, or we get a better answer from AJ on an ideal time/cycle to harvest.

**Comment by kbailey-noaa** [comment]
@kknee Closing this out.  We have a chunk of data from 8/22 - 29 that we can work with.  it looks like they are 3-hourly rather than hourly, but this is good enough for demonstration purposes.   (This close-out assumes the harvest cycle changed to 2x/day).
