### ISSUE TITLE
Add PacIOOS Mariana Island winds

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#130]
- [ ] Mariana Islands Winds - WRF/ARW; 6-day, hourly forecast, 3 km resolution

**Comment by kbailey-noaa** [comment]
@kknee This is low priority.  If too expensive, will defer to next year.

**Comment by kknee** [comment]
@kbailey-noaa these are on EDS production and just added to the dev OceansMap instance

**Comment by kbailey-noaa** [comment]
@kknee  I don't see these in the dev OceansMap.

**Comment by kknee** [comment]
yeah...I added them to the wrong key, will get that fixed today.

**Comment by kknee** [comment]
these are looking good on dev, will promote to production: 
![image](https://user-images.githubusercontent.com/196868/57648347-4b91cf00-7593-11e9-8e99-9b2bbccfaebb.png)

**Comment by kbailey-noaa** [comment]
@kknee @Bobfrat 
I couldn't get the mariana winds layer to load. Turns out it loads only if it's within the map view.  I had the default (Conus) view open and it gave me an error when I turned it on.  FYI this is one of those bugs we've seen before and I thought had been fixed.

Also the TOC layer name needs to be updated to PacIOOS Mariana WRF Winds.

**Comment by kbailey-noaa** [comment]
@kknee The name was fixed but wasn't pomoted to production

**Comment by kknee** [comment]
@kbailey-noaa name of this layer is all set
