### ISSUE TITLE
Add CNAPS currents

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#131]
@kknee If this is already available in EDS then implement with release 1.2.2.  Otherwise will just combine with the other CNAPS issue.

Label as a SECOORA layer.

**Comment by kbailey-noaa** [comment]
@kknee Sounds good.

**Comment by kknee** [comment]
@kbailey-noaa this is all set

**Comment by kbailey-noaa** [comment]
Great! Closing.
