### ISSUE TITLE
CBIBS missing data

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#132]
In dev: http://dev.oceansmap.com/eds/#
@kknee CBIBS buoys are very helpful for comparing OFS output, and I was hoping to use these for the demo on 7/24.  Is it possible to resolve this before then?

It looks like the CBIBS buoys stopped updating 5/22 but the data are updating on the CBIBS site.  Not sure if something happened to the API?
![cbibs_stingray](https://user-images.githubusercontent.com/11823385/42645616-7c400d68-85cc-11e8-8c0f-16a1d4516155.PNG)
vs https://buoybay.noaa.gov/locations/stingray-point

Also I noticed some variables are missing.  e.g. Gooses Reef water temp is missing from the Viewer list but it's a variable on the CBIBS site (https://buoybay.noaa.gov/locations/gooses-reef) - although granted it hasn't updated since 7/10:
![cbibs_gooesesreef](https://user-images.githubusercontent.com/11823385/42645511-39e4db2e-85cc-11e8-88ed-f04dde8e2fd0.PNG)

**Comment by kbailey-noaa** [comment]
CBIBS data were updating, but are now 5 hours old.  The CBIBS website shows data are recent.  e.g. Gooses Reef in EDS says last timestamp was 0500, but CBIBS website says 1000.

**Comment by Bobfrat** [comment]
Should be harvesting all the latest data now. 

I've identified the missing variable issue. There was a week or so when some of the variables weren't reporting from the CBIBS data service so our daily netCDF files were lacking these variables and therefore removing them from the aggregation we're using. We'll need to refactor the harvester code a bit so I'm not confident this will be fixed by Monday

**Comment by kbailey-noaa** [comment]
@Bobfrat Looking at dev, CBIBS is vastly improved!  Latest data and all variables are showing up for all the CBIBS stations.  Keeping this open per your previous comment, though.

**Comment by Bobfrat** [comment]
@kbailey-noaa The CBIBS aggregations have been fixed. Thanks @cheryldmorse!

**Comment by kbailey-noaa** [comment]
Excellent! It looks great.
