### ISSUE TITLE
OFS missing chunks of data

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#133]
I ran the animation (in eds.ioos.us) for CBOFS water temp and DBOFS salinity and currents - all were missing a large chunk of data -- for hours 09:00 through 21:00 every day.  Saw the same issue in dev.

CBOFS water level and CREOFS salinity worked though.

**Comment by kbailey-noaa** [comment]
@Bobfrat This is a more immediate issue, since I hoped to announce the model viewer updates to the OFS users.  I just looked at CBOFS WT and still see data from 0900 - 2000 are missing.  Do you have a status?

**Comment by kbailey-noaa** [comment]
Also finding that CBOFS layers haven't updated today (8/2) since 0200.  DBOFS salinity only shows 1 hour of forecast data (the data cut off at 8/2 1300).

**Comment by kknee** [comment]
@kbailey-noaa gaps are gone as of 8/8.  The 3D layers do have a shorter forecast.  The solution here is to update how frequently we harvest the data, if you'd like us to look into that, can we close this issues and open a new one for that specific task?

**Comment by Bobfrat** [comment]
@kbailey-noaa right now we're getting the 0Z runs daily for the 3D datasets

**Comment by kbailey-noaa** [comment]
Ok thanks.  I'll close this out since the original issue is resolved.  Not sure it's worth updating the harvest frequency, so will leave that alone.
