### ISSUE TITLE
Depth slider

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#135]
The dev version had a depth slider for adjusting sigma levels for active 3D layers.  I'm not sure what happens if I have multiple 3D layers active, but it was a nice feature that made adjusting depths a bit easier.  There were some issues - the slider activated a different sigma level layer than what was selected, and values at the top were 'bottom,' which was counterintuitive.  Would be great to have this feature available for the modelers to see.

**Comment by Bobfrat** [comment]
I agree the depth slider is a nice improvement. There are some technical hurdles but we're going to try to get it right for Monday.

**Comment by kbailey-noaa** [comment]
@Bobfrat @cgalvarino Do you have a status on this? I'm feeling this is less critical for immediate release.  I'm demoing to the OFS modelers on 9/4, and at a NOAA Modeling Fair on 9/12.  I can move the due date on this one to 8/27.  LMK what you think.

**Comment by Bobfrat** [comment]
@kbailey-noaa we're still battling the details with this one. Some more time would be appreciated. Should certainly be able to get it done by 8/27

**Comment by cgalvarino** [comment]
I agree.  And it would be helpful if you had a cycle or two @kbailey-noaa to test things out along the way if you were interested.

**Comment by kbailey-noaa** [comment]
@cgalvarino definitely - just give me a heads up on when to test.  I'm on leave next week but am available after that.

**Comment by kbailey-noaa** [comment]
@Bobfrat If I turn on CBOFS 3D water temp and currents, then hit the magnifying glass in one of the layers to zoom to the region, currents are displayed on top of the water temp, which is good.  But if I adjust the slider to 0.175 sigma, the currents vectors disappear behind the water temp layer.  They only rearrange to the correct order if I zoom in or out after setting the depth, or if I click/drag to move the map.

**Comment by kbailey-noaa** [comment]
@Bobfrat for users not familiar with sigma as depth - esp nonmodelers - is it possible to include the word "depth" somewhere in the slider display?

**Comment by cgalvarino** [comment]
I'll look at https://github.com/asascience-open/IOOS-EDS/issues/135#issuecomment-416598220 (the vector stack order after a depth change).

**Comment by kbailey-noaa** [comment]
Vector stack order after depth change is resolved.  Closing this.
