### ISSUE TITLE
Observation time series default setting

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#136]
When I click on a station in the map the time-series defaults with data.  This is distracting when I'm trying to compare a different dataset than what the default shows.  I have to go turn off the obs layers.  Can you change the default to show no data?  It would be much cleaner that way.  The message in the empty time-series plot is good - it points the user to select a parameter.

Also found a bug where the default active layer keeps reactivating when I zoom in/out on the map, even though I had turned it off.

**Comment by kbailey-noaa** [comment]
To add, if I'm comparing model vs obs, any time I choose a different time stamp the default obs layer keeps turning back on.

Also, if I close the plot window entirely, and reopen it later to compare other things, the station obs window still retains a 'memory' of what parameters I had turned on.  Recommend wiping this clean if possible - if I close the window it should also deactivate any parameters that are turned on.

**Comment by Bobfrat** [comment]
Apologies, this was a feature we added. On dev you'll notice we don't make any default plots anymore unless a theme is selected. Let me know what you think

**Comment by kbailey-noaa** [comment]
@Bobfrat much better!
FYI - I discovered that when I choose a variable-based theme (e.g. winds) the obs layer (e.g. NDBC buoys) in the TOC indicates it's active but the markers don't actually show up in the map.
![theme](https://user-images.githubusercontent.com/11823385/43399705-bd222cba-93d9-11e8-9943-d261b760dee0.PNG)

**Comment by kbailey-noaa** [comment]
@Bobfrat got it, thanks! Closing this.
