### ISSUE TITLE
GLERL layers

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#137]
All the GLERL layers aren't showing data.  The THREDDS catalog shows the last netCDF file is dated 7/13 although I'm able to turn on layers going back to 7/20 (and then the data disappears after that).

Is this the GLERL source? https://www.glerl.noaa.gov/res/glcfs/glcfs.php?lake=s&ext=sfcur&type=N&hr=00
If so, data are updating on this page.  Is this a harvester issue?  These layers are great for comparing to Great Lakes OFS in a demo.

**Comment by kknee** [comment]
@kbailey-noaa this is the EDS team's highest priority at the moment.  GLERL made some changes to their files last week that impacted our harvest.

**Comment by kbailey-noaa** [comment]
This is fixed, so closing.
