### ISSUE TITLE
Obs station markers all faded

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#139]
I thought obs markers were faded if no data within last 4 hours.  In dev, NERRS stations show data 1 hour old (for several) but markers look faded.  e.g. Menauhant near Falmouth, MA.  
In prod and dev, I turned on the NDBC & partner stations layer and found the same issue - ALL stations were faded but data are < 1 hour old.

**Comment by Bobfrat** [comment]
A fix has been deployed on dev. I'll be monitoring to ensure it doesn't creep up again.

**Comment by kbailey-noaa** [comment]
@Bobfrat Looks good.  Closing this.
