### ISSUE TITLE
NERRS parameters + values

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#140]
Seen in both dev and prod:
Unclear what some of the parameters and associated values are. 
e.g. "F ChlFluor" = 0 1? 
![menauhant](https://user-images.githubusercontent.com/11823385/43156128-4aed0430-8f47-11e8-804e-53f16540cc51.PNG)

**Comment by Bobfrat** [comment]
Looks like the "F" variables are flags. I'll remove them from the popups

**Comment by Bobfrat** [comment]
The flag variables have been removed from the NERRS stations

**Comment by Bobfrat** [comment]
@kbailey-noaa yeah I jumped the gun. Should be set now
