### ISSUE TITLE
Ensure currents are on top of other layers

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#141]
Seen in dev:  If I activate currents and water level/temp/salinity (non-vector layers), the current vectors get buried.  Please bring the vector layer to the top as a default.
In prod (version 1) this is not an issue.

Dev:
![cbofs_buriedvectors](https://user-images.githubusercontent.com/11823385/43158822-ae6d7740-8f4e-11e8-80a4-3ee73c1493a6.PNG)

**Comment by Bobfrat** [comment]
Fixed on dev site

**Comment by kbailey-noaa** [comment]
@Bobfrat This came up again in the production (and dev) versions.  Looks like it reverted back so current vectors are hidden again.  Possible to fix ASAP?

**Comment by Bobfrat** [comment]
Yes I will look into it right now
