### ISSUE TITLE
Great Lakes OFS not updating

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#143]
Great Lakes OFS show no data since July 14.
LMOFS - all layers
LEOFS - all layers
For some reason LOOFS water level is recent though.

**Comment by kknee** [comment]
@kbailey-noaa - this is an EDS issues, the team is already aware and working on a fix.  GLERL is slightly higher priority and a fix is already being tested on staging. GLERL changed their file names and model time steps so we had to make an adjustment to our harvester.  OFS will come directly afterwards.

**Comment by Bobfrat** [comment]
@kbailey-noaa They should be updating now

**Comment by kbailey-noaa** [comment]
@Bobfrat I see them.  Why does the OFS data get truncated by 36 hours?  Looking at it now (8/2 10:45 ET) / 9:45 CT) and the OFS forecast data goes out to 8/4 1900 CDT but the plot shows data ending at 8/3 0600 ET / 0500 CDT.

From CO-OPS OFS site: LMOFS water temp forecast guidance:
![lmofs_wtfrxt](https://user-images.githubusercontent.com/11823385/43591575-a690cc30-9641-11e8-81bf-09c3ceaf9941.PNG)

From dev:
![lmofs_eds](https://user-images.githubusercontent.com/11823385/43591627-baabc15c-9641-11e8-9264-4217ef93f7c8.PNG)

**Comment by kbailey-noaa** [comment]
@Bobfrat ahhh, maybe this is related to issue #146??

**Comment by kbailey-noaa** [comment]
Now those LMOFS WT data are truncated by 18 hours, not 36.  Certainly an improvement.

**Comment by Bobfrat** [comment]
@kbailey-noaa I need to check how often and when we're harvesting. May be a latency issue.

**Comment by kknee** [comment]
@kbailey-noaa the Great Lakes OFS (and GLERL) are fixed.  If this is another latency issue, similar to thee 3D forecasts, can we close and reopen a general issue on that topic?

**Comment by kbailey-noaa** [comment]
@kknee @Bobfrat I checked LMOFS today and it shows the full forecast period.  Closing this, and if I see the data are truncated again I'll just open a separate issue, per Kelly's request.
