### ISSUE TITLE
Timestamp discrepancies

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#144]
TOC time label ("Valid time") shows map time that I set but the map displays the timestamp of the most recent available data (and also displays those last-available data within the map itself).  This is a problem for instances when I set a map time for which there aren't any data. The TOC shows map time but the data displayed are the last-available, which could be several days old.  

CREOFS currents shows this issue well - there are actually 3 different timestamps shown.  1) The slider shows the time I set it to; 2) The TOC shows the map time, but for some reason this doesn't match the slider time; and 3) the obs window shows the timestamp for the last available data, which happens to be several hours old.  This is confusing.
![maptimeissues](https://user-images.githubusercontent.com/11823385/43161993-b2205f16-8f57-11e8-8fe1-305b6ed86638.PNG)

I think the issue is that if there are no data for the timestamp I select, the map automatically displays the most recent data available.  But this causes discrepancies.  Recommend changing this - just return no data/displays for a time when no data are available.  And ensure the TOC reflects that there are no data for that timestamp.

**Comment by kbailey-noaa** [comment]
@Bobfrat Another example, using NANOOS CMOP SELFE Bottom temp:
The plot window timestamp matches the last available data in the time-series, which is good.  The slider time is what I set to.  The issue is the TOC valid time is some weird timestamp that's 12 hours ahead of the last available data/plot window timestamp, and 8 hours behind the set map time.  Not really sure what a good solution is here...  If the Valid time in the TOC is the timestamp for the last available data then this is confusing unless a user drops a virtual buoy and sees there are missing data in the TS plot.  Also, the TOC valid time is very easy to miss.
But if the map doesn't show return any data (rather than showing last-available) then the user might think the Model Viewer isn't working.  I think we need some indication that there aren't data available for the chosen timestamp.  And/or some indication of when the last-available data are.
![cmopselfe_timestamp](https://user-images.githubusercontent.com/11823385/43595600-16a7914e-964b-11e8-9c28-bbe7a95c19d5.PNG)

**Comment by kbailey-noaa** [comment]
@Bobfrat 
Also, I discovered from several plots (LOOFS currents shown for example) that the data plotted in the map = 1 hour behind the timestamp I choose.  So when I choose a map time of 11:00 and drop a virtual buoy, the plot window and profile plot show a timestamp of 10:00.  The TOC valid time = 11:00 though (not shown in this screenshot).
![loofs_timestamp1hroff](https://user-images.githubusercontent.com/11823385/43596032-2325c200-964c-11e8-9a78-21b068709086.PNG)

**Comment by Bobfrat** [comment]
@kbailey-noaa 

> I think the issue is that if there are no data for the timestamp I select, the map automatically displays the most recent data available. But this causes discrepancies. Recommend changing this - just return no data/displays for a time when no data are available. And ensure the TOC reflects that there are no data for that timestamp.

With many models not running at 1 hour intervals I suspect if we dont show map/data unless there is an exact match in time it will be a poor user experience. Instead I think we need to define a threshold.

**Comment by kknee** [comment]
@kbailey-noaa  - I agree with @Bobfrat on this one.  This can get confusing if there is no data because of the model time step.

**Comment by kbailey-noaa** [comment]
Good point, I agree

**Comment by mwengren** [comment]
> With many models not running at 1 hour intervals I suspect if we dont show map/data unless there is an exact match in time it will be a poor user experience. Instead I think we need to define a threshold.

FWIW, this is similar to the 'seamless time coverage' approach used by nowCOAST to account for inexact time step values for individual datasets in a time-enabled service.  If you want to read more, see: https://nowcoast.noaa.gov/help/#!section=time-enabled-map-services (section titled 'Seamless Time Coverage').  It works quite well and avoids the pitfall @Bobfrat was referring to of no data without an exact match.  

Might not be so straightforward in THREDDS/WMS/ncWMS though, if that is what is being used, not sure....

**Comment by Bobfrat** [comment]
thanks @mwengren. This sounds similar to what we're currently doing but sometimes the closest available image/data isn't very close. We try to get around the issue by always displaying the timestamp of the layer in the TOC so the user knows what they're looking at. That can cause confusion to the user though when the TOC says one time stamp and your map time says another. It gets even more confusing when we have some data/GFI issues so the map image and profile data are out of sync, but I think we've got a handle on that now.

**Comment by mwengren** [comment]
I think the nowCOAST approach is dependent on the ingest processes being pretty stable (and monitored 24 x 7), so there's little chance of a dataset going un-ingested for a long period of time and causing some of the issues @kbailey-noaa found with the old time labels.  

Also their services don't archive data in quite the same way as EDS, so if a dataset does lapse in ingest, it is dropped from the service after the normal time window for it passes, and there's no data to display.  Anyway, I think a timecoverage is probably the right approach to take, otherwise your time control will become unwieldy, and users will have a hard time comparing two layers with slightly different valid times for granules.

**Comment by kbailey-noaa** [comment]
@Bobfrat Is this resolved, then?  Did you define/apply a threshold?  Thanks @mwengren for the insight!

**Comment by kbailey-noaa** [comment]
@Bobfrat @kknee To revisit - Is this a heavy lift, or are you working on a solution?  Should I move it to a later milestone (2.1?) or is this close to done?

This might be a mix of 2 different issues: 1) The TOC Valid Time defaulting to last available data for cases when there are data gaps and 2) West Coast layers showing a 'valid time' that is several hours off from the map time and time-series timestamp.  

For #1 - I understand the 'valid time' only corresponds to the date/time of the image shown in the map as opposed to the map time that I set.  ...which is fine, and as @Bobfrat said this likely requires a threshold to constrain that 'last available' data to something reasonable.
For #2 -  This is the bigger issue, which I'm still seeing in dev.  CREOFS currents show a 'valid time' that is 23 hours ahead of the map time.  There aren't any data gaps, so this is unrelated to #1.  Same for SELFE bottom water temp, except those data are 8 hrs off.

**Comment by kbailey-noaa** [comment]
Given that 2.0.2 closed, I'm moving the remaining 2.0.1 issues to 2.0.3.

**Comment by Bobfrat** [comment]
@kbailey-noaa the timestamps should be in sync now
