### ISSUE TITLE
TS plot issues for instances of missing data

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#146]
For datasets where there aren't recent data - the Time-series plot time range zooms in as I choose dates closer to and a couple days beyond the data cutoff.  Would like to keep the time range fixed, and simply show a truncated data curve.  For the most recent timestamp, the time-series and profile plots should be empty (as opposed to showing last-available data - this is already described in issue #144).  Currently this isn't consistent - the profile plot shows last-available, but the TS is empty.

Example:
LMOFS water temp hasn't updated since 7/14.  If I set the slider range to 'last 30 days' and choose a date of July 7, I get data in both profile and TS plots (as expected) and the TS plot range is from July 4 - 10 (a 7-day range) as expected:
![lmofs_july7](https://user-images.githubusercontent.com/11823385/43163121-1e1eb2aa-8f5b-11e8-8c3a-b83e64a7ccea.PNG)

But if I choose dates closer to July 14 when the data are cut off, the TS plot zooms in and reduces the time range - from a 3-day range down to 24 hours - yet it never shows dates beyond July 14 when the data aren't available.  Unless I choose a date beyond 3 days of the last-available data (e.g. July 18) - then I get a blank TS plot, which is expected.  

Here is the July 17 plot - notice the time range is down to 24 hours:
![lmofs_july17](https://user-images.githubusercontent.com/11823385/43163371-eb7a5b00-8f5b-11e8-9d78-b81a71ffc78b.PNG)

**Comment by cgalvarino** [comment]
Hi, Kathy.  We're trying this on for size:
* Tightening the request to only look back 2d and ahead only 12h (originally it was +/- 3.5 days).
* Always showing this time period in graphs no matter the data availability.
* Adding a new shaded area that represents forecasted times, basically anything >= now.

This is what it will look like.
![snag-0001](https://user-images.githubusercontent.com/180985/43410499-1388c45e-93f5-11e8-896e-ad4585159219.png)

Do you have any initial reactions before we deploy this somewhere?

**Comment by kbailey-noaa** [comment]
@cgalvarino Visually, it looks great.  I like the shaded area fore forecasted times.

I'm a little concerned about limiting the look ahead to only 12 hrs - this isn't much data if a user wants to be able to compare forecast data - e.g. if they want to see how a forecasted weather event might be handled in one model vs another...  The +/- 3.5 days range was less constraining, in that sense.  If there's an issue with processing time etc, then perhaps just expanding the 12 hrs to 24 hrs would suffice.

As for always showing this time period no matter the data availability - I agree with this - data availability shouldn't change the graph's x axis.   (I assume the option to zoom will stay intact).

**Comment by Bobfrat** [comment]
Ok I deployed this to the dev site
http://dev.oceansmap.com/eds/

**Comment by kbailey-noaa** [comment]
@cgalvarino I see what you mean.  FYI - For the purpose of our IOOS oceansmap instance, we're focused more on it being used as a tool for viewing/accessing/comparing model output rather than a portal to view obs data as well (like the MARACOOS portal).  Obs are mainly there for skill assessments/comparisons, as opposed to viewing the data for navigation or other decision making purposes.  So it would definitely make more sense to look ahead 12 hr if we were gearing this towards a tool for viewing obs, but since we gear it more for models it doesn't work as well.  That said, when I demo I'll try to get user feedback on that.

@Bobfrat and @cgalvarino- seen in dev:   I'm finding that when I change the time slider range (e.g. to past 30 days) it automatically changes the date/time to the first day in that new range.  
I chose DBOFS Salinity in the TOC (the map time is default therefore is set to 'now').  Then I changed the slider range to past 30 days.  The map time automatically changed to July 1 and the layer disappeared because data don't go back that far.  This is an issue because I have to keep resetting the map date/time to 'now.'

**Comment by Bobfrat** [comment]
@kbailey-noaa so a fix would be to leave the map time unchanged when selecting a new range as long as the current map time is within the new range. And if the user selected a custom range totally outside of the current map time, should we put the map time at the start, end, or middle of the new range?

**Comment by kbailey-noaa** [comment]
@Bobfrat Yes to the fix (first sentence).  If the user selects a custom range outside the map time, then default to the start of the new range.

**Comment by kbailey-noaa** [comment]
@cgalvarino @Bobfrat I had a hand-to-forehead moment.  Please don't limit forecast data in the plot - show all data that is available for a model.  I was wondering why Great Lakes OFS layers were cut off before the forecast period ended and realized it might be related to this issue.  Although I realize you rolled that 12.5 h ahead idea back, so maybe not... Either way, we definitely want to show all forecast data available.

**Comment by cgalvarino** [comment]
The requests were rolled back to +/- 3.5 days.  So all requests have always been limited to 3.5 days ahead of the map time.  As far as I know we've never shown all available FC data for a given model.

**Comment by kbailey-noaa** [comment]
Ok, I do see that other layers are not truncated, so it's just OFS.

**Comment by Bobfrat** [comment]
@kbailey-noaa the fix described above from 3 days ago has been deployed
