### ISSUE TITLE
TS pops up randomly 

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#147]
Seen in dev:
Turned on CBIBS and CBOFS currents layers.
Selected Gooses reef, and in parameter pane, turned off AT (was turned on as default), then chose current speed and direction and the CBOFS layer - these plotted in the TS.
Then I closed the time-series TS plot window.  I deactivated CBOFS currents layer in the TOC, and suddenly the TS plot pops back up, with air temp, and current dir and speed parameters selected from CBIBS only.

**Comment by Bobfrat** [comment]
This issue was moved to asascience/OceansMap#3294

**Comment by Bobfrat** [comment]
Fixed on Dev 
http://dev.oceansmap.com/eds/

@kbailey-noaa do you want me to deploy the latest and greatest to production as we go?

**Comment by kbailey-noaa** [comment]
@Bobfrat Yes, deploy as we go. Thanks!

**Comment by Bobfrat** [comment]
@kbailey-noaa @kknee this has been fixed on dev. Production release coming soon.

**Comment by Bobfrat** [comment]
@kbailey-noaa this has just been deployed to production
