### ISSUE TITLE
Virtual buoy dropped whenver shift+zoom control used

### ISSUE THREAD

**Issue by mwengren** [asascience-open/IOOS-EDS#148]
Whenever I use the SHIFT+Left Mouse Button+Draw Zoom Box interaction, a virtual buoy is dropped when I release the zoom box (roughly at the stopping point of the zoom box, although not precisely).  I don't think this is intended, and it makes for an unexpected result for the user.  

The shift zoom is a pretty common web GIS map command, probably provided by the mapping API you use for Oceansmap under the hood, but I think the event handling code for virtual buoy drop must be conflicting with the out of the box shift+zoom event.  It should just zoom the map and not drop the buoy. 

I tried this on both Firefox and Chrome and on both the Dev and Prod EDS.

**Comment by Bobfrat** [comment]
@mwengren good catch, this was a bug in Leaflet that has since been fixed. Should be all set now. I'll make sure this propagates into other OceansMap portals as well

**Comment by kbailey-noaa** [comment]
I tested this and is fixed in dev (and prod) so closing.
