### ISSUE TITLE
Salinity - missing units

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#149]
Salinity units are missing from displays (e.g. time-series plot, rollover pop-up of data, etc).

![cbibs_salinity_nounits](https://user-images.githubusercontent.com/11823385/43406616-a5e9fe86-93ea-11e8-9f32-5d888523b135.PNG)

**Comment by Bobfrat** [comment]
@kbailey-noaa Looks like the units attribute is missing from many of the OFS models salinity variables.

https://opendap.co-ops.nos.noaa.gov/thredds/dodsC/NOAA/CBOFS/MODELS/201807/nos.cbofs.fields.n006.20180704.t12z.nc.html

I'm assuming the units are 'PSU' or 'PPT'?

**Comment by Bobfrat** [comment]
In the meantime, we're adding in PSU for these salinity layers that are missing units

**Comment by kbailey-noaa** [comment]
So this is interesting...  I heard back from CO-OPS, who passed on the issue to the ROMS developers.  They purposefully do not use any units/label for salinity, so the units attribute will not be added.  However, CO-OPS OFS graphics do include PSU as a label in the legend.  I've asked AJ if they plan to omit this.  For now we will leave PSU in the IOOS Model Viewer, but there is a potential that it may get removed in the future.

From Hernan Arango:
"The reason why there is not units for salinity is because it is non-dimensional.  We still use the UNESCO (1985) equation of state.  See:
https://www.myroms.org/forum/viewtopic.php?f=30&t=294&p=680&hilit=PSS#p680
This will be changed when we use the new international equation of state TEOS-10.  See:
https://www.myroms.org/forum/viewtopic.php?f=32&t=1214"

Noted in that first link: "The bottom line is that salinity has always been a ratio and does not have physical units. The use of the term PSU should not be permitted in the field and certainty not used in published papers."

**Comment by Bobfrat** [comment]
Very interesting and good to know!

**Comment by kbailey-noaa** [comment]
I see it's in dev, so closing.
