### ISSUE TITLE
User feedback: Themes missing obs

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#152]
From james.clontz@noaa.gov:
"I used to be able to select observations and themes and the station data would be displayed. For example, selecting NDBC observations & wind theme, it would display the data in the middle of the station; however, since you've updated the data layers, the station circle disappears when selecting the wind theme and only the model data are shown."

@Bobfrat I really thought I had this issue documented somewhere because I noticed something similar.  Can't seem to find it though.  To add to Jim's comment, if I just choose the wind or waves themes the NDBC obs layer is activated but none of the data markers show up.  Seen in dev and prod.

![theme2](https://user-images.githubusercontent.com/11823385/43599458-a47d344c-9655-11e8-86ec-15eb3a6de92b.PNG)

**Comment by Bobfrat** [comment]
This is the issue you mention:
https://github.com/asascience-open/IOOS-EDS/issues/136

> @kbailey-noaa Yes this is a bit confusing because when a theme is activated we try to show realtime data for that parameter on the map. But there are some times when the realtime data lags behind a bit, outside of our 90 minute threshold from the map time for showing data. If you step the map time back an hour you can see what we're trying to do.

As for solutions, I think we can either loosen up the thresholds or move the current map time back an hour so we have a better chance of seeing the current conditions

**Comment by kbailey-noaa** [comment]
@Bobfrat lol thanks, it's been a long week...  I'll let Jim know about this.

**Comment by kbailey-noaa** [comment]
Jim (a user) discovered that the NDBC and CO-OPS obs haven't displayed since Jan 28 0300.  I checked and time-series data are available, so it isn't a missing data problem.

**Comment by kbailey-noaa** [comment]
I can't figure out how to get obs to show up at all, when selecting a variable theme.  Even stepping back to previous timestamps within that 90 min threshold.

**Comment by Bobfrat** [comment]
@kbailey-noaa The theme obs marker service is back.

![Screen Shot 2019-11-14 at 8 17 29 AM](https://user-images.githubusercontent.com/5702672/68860292-408d3800-06b7-11ea-874e-b2586c00deac.png)
