### ISSUE TITLE
SECOORA SAB GOM currents not updating

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#154]
...for maybe a year.  No data for any timestamp I chose over past year.

**Comment by kbailey-noaa** [comment]
CNAPS might be replacing SABGOM.  I'm going to check with SECOORA to see what they want to do (remove SABGOM or keep).

**Comment by kknee** [comment]
@kbailey-noaa I'll check on SAB_GOM status.  

I have not heard anything through the grapevine about CNAPS.  If there is an issue with availability of SAB_GOM I'll let you know and we will remove.

**Comment by Bobfrat** [comment]
SABGOm has been removed from eds.ioos.us
