### ISSUE TITLE
PacIOOS Guam WW3 Dir in Global category..??

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#155]
A layer called PacIOOS Guam WW3 Wave Direction is in the Global section of the TOC.  The layer does show global direction data.  Is it mislabeled??

![pacioos_guam](https://user-images.githubusercontent.com/11823385/43600653-34a07478-9659-11e8-84f1-cb7966e93488.PNG)

**Comment by Bobfrat** [comment]
Looks to be mislabeled.  It should be NOAA WW3 Wave Direction

**Comment by Bobfrat** [comment]
This layer is properly labeled now
