### ISSUE TITLE
Active tropical cyclone layer disappeared

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#157]
@kknee @Bobfrat 
...any way to get that back asap?  Lane is about to hit Hawaii and I hoped to capture screenshots for the upcoming demos.

**Comment by Bobfrat** [comment]
@kbailey-noaa Should be there in the global category. 

![screen shot 2018-08-22 at 9 54 12 am](https://user-images.githubusercontent.com/5702672/44467618-56fe2e00-a5f1-11e8-8e77-b3e02bb30f81.png)

**Comment by kbailey-noaa** [comment]
AH thanks!
