### ISSUE TITLE
Legend units don't change

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#158]
When I set the Unit System to "US" in the hamburger menu and turn on a layer, the legend is still in metric.  The plots are in US though. 

![units_wt](https://user-images.githubusercontent.com/11823385/44744877-2a0bb880-aad4-11e8-8d01-15e134bb1d63.PNG)

**Comment by Bobfrat** [comment]
@kbailey-noaa should be all set now
