### ISSUE TITLE
Closing plot windows

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#161]
For the 3D layer, if I close the profile plot, it also closes the time-series plot window automatically.  Please 'unlink' those plots so I can close one or the other.  I'm finding if I want to view the time-series only and the map then the profile plot is in the way.

**Comment by Bobfrat** [comment]
And conversely, you'll need a way to bring the profile plot back into the picture if you want it back.

**Comment by kbailey-noaa** [comment]
Right!  Maybe an option to minimize instead.

**Comment by kbailey-noaa** [comment]
I saw in dev the minimize option is there.  Looks good!  Is that possible for the time-series plot too?

**Comment by cgalvarino** [comment]
Hi, @kbailey-noaa.  The tricky part about adding a minimize option to the timeseries is how to get rid of the pulsing dot when the user really doesn't want it anymore.  A way to get the same result that you describe above is to add the virtual buoy to your map (and the TOC) so that you can show / hide the graphs at anytime.  Maybe the add button is too well hidden?

**Comment by kknee** [comment]
@kbailey-noaa thoughts there?  Would you prefer that we minimize TS plot and leave pulsing dot on the map?

**Comment by kbailey-noaa** [comment]
@kknee @cgalvarino I'd prefer we minimize the TS plot and leave the pulsing dot on the map.  I like that the way to get rid of the dot is to fully close the TS window.  It also acts as a reminder that the open (but minimized) TS window pertains to that pulsing dot.  
For me, minimizing a TS or profile plot is just a temporary action so that I can see more of the map (e.g. if there is a hurricane track overlaid on some model output that I want to examine).  I don't think there's a need to go beyond that and keep graphs associated with virtual buoys.

**Comment by Bobfrat** [comment]
@kbailey-noaa, this implementation has been deployed to the dev site. Can you have a look and let us know what you think?

**Comment by kbailey-noaa** [comment]
@Bobfrat When I minimize the time-series, both plots disappear (well, they minimize).  When I minimize the profile plot, only that plot disappears.  Is that on purpose?  Not a showstopper, just curious if that was intentional.  But it works!

**Comment by cgalvarino** [comment]
Hi @kbailey-noaa what you describe is how it was intended.  The profile graph is really dependent on what is selected in the parameter checkbox area, and I didn't want the user to lose that point of reference.  That, and I didn't think about a user wanting to minimize / restore the profile and time-series graphs independently!  :)

**Comment by kbailey-noaa** [comment]
Roger that!

**Comment by kbailey-noaa** [comment]
@Bobfrat I think this resolves the issue.  Closing this.
