### ISSUE TITLE
NYOFS missing hrs of data

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#162]
This seems to have been an issue for at least a year, and has actually improved.  We were only getting one data point per day, but since August 14 we are getting a small window of hourly data: from 14:00 - 19:00.  See currents below:

![nyofs_missingdata](https://user-images.githubusercontent.com/11823385/44797390-18cab680-ab7d-11e8-937b-2a93b28f6bef.PNG)

**Comment by kknee** [comment]
@kbailey-noaa this one is all set: 

![image](https://user-images.githubusercontent.com/196868/70940438-4f4d6e80-2018-11ea-8399-82e5d252ee60.png)
