### ISSUE TITLE
THREDDS - metadata cleanup

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#169]
IOOS has an 'attribution project' that will result in updates to the [netCDF profile](https://ioos.github.io/ioos-netcdf/ioos-netcdf-metadata-description-v1-1.html) (list of required attributes to improve identification of ownership of datasets).  This will impact the EDS netCDF files, which will potentially need to be updated to adhere to these newer guidelines.  We will need to determine what updates are needed, especially considering not all source netCDF files that EDS harvests will necessarily be updated to follow these updated guidelines (e.g. CO-OPS struggles with this).  Might need to at least update the ncml files with proper attribution.

**Comment by Bobfrat** [comment]
@kbailey-noaa wrt attribution, I'm looking for some guidance on the "publisher" (Name of the person or group that distributes the data files) metadata fields. With files from all different sources being harvested and redistributed by IOOS/RPS who should we attribute the publisher to be? Would it be the institution EDS originally harvested from? RPS? IOOS?

Or would you rather see RPS as a contributor?
```
contributor_name: RPS
contributor_email: devops@rpsgroup.com
contributor_role: DMAC
contributor_url: rpsgroup.com
```

**Comment by kbailey-noaa** [comment]
@Bobfrat  In short, IOOS should be the publisher since it's coming from the IOOS EDS THREDDS, and I like RPS as a contributor.  However, see the latest guidance at: https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
(Attribution section). This was recently updated by Micah, and we now have a contributor_role_vocabulary, so "DMAC" wouldn't be a valid entry for contributor_role.  I'm not sure which would be the most ideal vocab for RPS' contributor role though... I would suggest either use publisher, to indicate RPS is also in a publisher role, or perhaps processor (if the resource has been modified...not sure that quite fits).  Publisher is probably best, but am open to ideas.

I think the most important thing is to ensure we're following this updated metadata guidance since we're going to peddle this as the IOOS gold standard.

Can you please add @mwengren to this?  I'm unable to tag him in this thread and assume I don't have the permissions to add people.

**Comment by Bobfrat** [comment]
@kbailey-noaa totally agree, I like the role of custodian personally...

**Comment by Bobfrat** [comment]
Or maybe editor is better. We are reviewing and modifying attributes to improve the content

**Comment by kbailey-noaa** [comment]
@Bobfrat When I looked at this page (https://geo-ide.noaa.gov/wiki/index.php?title=ISO_19115_and_19115-2_CodeList_Dictionaries#CI_RoleCode)
I thought custodian seemed to imply an archival role, which made me think of a NOAA archival center.  (See the "applicable for" column).  Editor could work - hopefully it doesn't imply changes to the source data.  The definition is a little confusing to me.

**Comment by Bobfrat** [comment]
@kbailey-noaa How's this look for the IOOS attribution?

```
publisher_name: U.S. Integrated Ocean Observing System Program (IOOS)
publisher_email: webmaster.ioos.us@noaa.gov
publisher_address: 1315 East-West Highway
publisher_city: Silver Spring
publisher_zipcode: 20910
publisher_state: Maryland
publisher_country: USA
publisher_phone: (240) 533-9444
publisher_type: institution
publisher_url: https://ioos.us/
```

**Comment by kbailey-noaa** [comment]
@Bobfrat Here are my changes:

**publisher_name: U.S. Integrated Ocean Observing System (IOOS) --> I removed "program"** 
**publisher_email: data.ioos@noaa.gov (instead of webmaster email)**
publisher_address: 1315 East-West Highway
publisher_city: Silver Spring
publisher_zipcode: 20910
publisher_state: Maryland
publisher_country: USA
**publisher_phone: REMOVE because this field is recommended, not required, and I don't think it makes sense to put my # here.**
publisher_type: institution 
**publisher_url: https://ioos.noaa.gov**

**Comment by Bobfrat** [comment]
Noted, thanks!

**Comment by kbailey-noaa** [comment]
Part of THREDDS gold standard/upgrade task, which has been completed. We are now soliciting user feedback on their metadata, which might require minor changes.  Closing this issue.
