### ISSUE TITLE
Add Glider Tracks

### ISSUE THREAD

**Issue by Bobfrat** [asascience-open/IOOS-EDS#171]
@kbailey-noaa Ben LaCour asked if we could get Glider tracks into EDS so we could show models and Hurricane layers alongside Gliders.

**Comment by kbailey-noaa** [comment]
@Bobfrat @kknee @gitchrisadams  Please do not start work on this.  I have not heard about this though am not opposed to the idea.  What is the level of effort / cost associated with this?  We've already spent 30k of the budget and I don't consider this high priority.  I need to talk to Ben about this to understand where this requirement came from, but if this is low cost/low effort then we could potentially proceed.  COMT and THREDDS are highest priority this FY.  
For future reference - I don't want RPS accepting requirements and doing work (drawing from the EDS budget) at the request of users or other IOOS reps.  I need to ensure the work we're doing this year is within scope and budget.

**Comment by Bobfrat** [comment]
@kbailey-noaa Totally understood, just putting the issue out there for discussion and tracking. 

It's about a 15 min task that would be covered by the GliderDAC budget. An alternative would be putting relevant model/hurricane layers into the GliderMap.

**Comment by kbailey-noaa** [comment]
@Bobfrat Great! Let's move forward, then, with adding glider tracks to the Model Viewer.  Thanks!

**Comment by Bobfrat** [comment]
@kbailey-noaa You'll notice on the dev site that the gliders are in the Observations category. If happy, I'll promote to production site

**Comment by kbailey-noaa** [comment]
@Bobfrat Sorry, I missed this!  The tracks look good on dev, and I see regional tracks were promoted to production.  The Atlantic Gliders layer is hard to understand, though. It looks like all deployments going back to at least 2016 are shown, and a couple appear to have track errors (a couple lines radiating outward towards the north pole or Canada).  Is there a way to constrain the deployments shown?  Perhaps the default should be to show what is currently in the water, and if a user changes the date/time then the deployments within that timeframe would appear.

**Comment by kbailey-noaa** [comment]
@Bobfrat I see this was fixed, and regional tracks were removed!  Much better, everything looks great.  Closing this out.
