### ISSUE TITLE
LMHOFS - In Development layers

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#172]
Request from CO-OPS (Machuan Peng):
Lake Michigan and Huron Operational Forecast System is still in development in CO-OPS.  Now it is time for us to send the model evaluation request to the outside users.  I am not sure if IOOS could help put our model results to EDS so the users could get access to the visualization of the model for evaluation purpose.  This model has been run for almost half year.  Its webpage can be found at 
[https://tidesandcurrents.noaa.gov/ofs/dev/lmhofs/lmhofs.html](https://tidesandcurrents.noaa.gov/ofs/dev/lmhofs/lmhofs.html)
If IOOS can give us help, please let me know where I would send you the model output."

-- I asked Machuan for some additional requirements related to THREDDS/netCDF delivery, timing of the test period, parameters and 2D vs 3D, model output timeframe, and any USCG involvement.  From what I saw, the data are not published in the CO-OPS THREDDS server so I suspect you'd get a handful of netCDF files.

@kknee - On the latter, if USCG is part of the test group (or user group in general) I'd like to see if they might kick in funds for this integration, particularly since this was unplanned on our part.  If not, then this is higher priority than everything except WCOFS for this milestone.  Also, I don't want to harvest 3D if we don't have to, given time constraints.  (I'm assuming 3D is time-consuming, trickier to deal with.)  Not sure what Machuan's expectations are yet but I can probably negotiate that, considering CO-OPS doesn't display 3D right now anyway.  Just trying to balance CO-OPS needs/timing with our resources/level of effort.

**Comment by kbailey-noaa** [comment]
@kknee @Bobfrat 
Here are the CO-OPS requirements paraphrased from the email exchange you're on.  We can negotiate if this is onerous:
- Data are currently on the CO-OPS FTP server at ftp://tidepool.nos.noaa.gov/pub/outgoing/ofs/lmhofs/netcdf.  You can start harvesting the files from there, starting from 09/01/18.  (FYI the data gets into the server 4 cycles a day)
-- I asked if we can harvest once/day, since that's the current EDS harvest cycle.
- Keep harvesting the new netcdf files by cron job daily so the users can get them like from an operational OFS.  (Data will be published to the [CO-OPS THREDDS](https://opendap.co-ops.nos.noaa.gov/thredds/catalog.html) server soon).

- Parameters are water level, water currents and temperature.  
- 2D surface only

It appears testing should start as soon as this is ready, and will continue for a few months.

Please let me know what you think re: a timeline, level of effort, funding.

USCG reps are included on the evaluation list:  Possible to leverage their funds?
              Steve Keck,  steven.r.keck@uscg.mil
              Arthur Allen,  Arthur.A.Allen@uscg.mil

**Comment by kknee** [comment]
@kbailey-noaa as discussed, this source is on USCG integration list for July so we will hold off until then.

**Comment by kbailey-noaa** [comment]
Update: LMHOFS now integrated in EDS. Please replace LHOFS and LMOFS with LMHOFS.

**Comment by kknee** [comment]
@kbailey-noaa I think we can close this, removal of salinity parameter is in a separate issue

**Comment by kbailey-noaa** [comment]
Agree!
