### ISSUE TITLE
Disable default layer

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#173]
Do not activate the NOAA RTOFS (strided) layer when the IOOS Model Viewer is first opened.  Leave it as a blank map.  This is throwing GA stats and if the layer has an issue with it (like it does now) then it doesn't look good.

**Comment by gitchrisadams** [comment]
**This is one dev:**
http://dev.oceansmap.com/eds/

**Comment by gitchrisadams** [comment]
This is on production:
https://eds.ioos.us/

**Comment by kbailey-noaa** [comment]
@gitchrisadams thanks!
