### ISSUE TITLE
EDS thredds server URL

### ISSUE THREAD

**Issue by Bobfrat** [asascience-open/IOOS-EDS#174]
@kbailey-noaa 
We discussed potentially using tds.eds.ioos.us. I've set it up for the time being but we can change that to whatever we please. Just let me know!

**Comment by kbailey-noaa** [comment]
@Bobfrat After discussing internally we decided to keep it as eds.ioos.us.  No change needed.

**Comment by kbailey-noaa** [comment]
Will remove from this milestone but keep open until we finalize.

**Comment by kknee** [comment]
two steps here: 

1. Get RPS IT to switch over the domain so that eds.ioos.us/thredds points to what is now tds.eds.ioos.us
2. Update all source info buttons to point to the main catalog at eds.ioos.us/thredds until we can update all individual URLs for sources

**Comment by kbailey-noaa** [comment]
@kknee We wanted to keep the URL as eds.ioos.us/thredds to keep URLs consistent (e.g. like https://gliders.ioos.us/thredds/).  Per the Apr 3 comment (though I probably could've been clearer).  Not sure if I misread your two steps note?

**Comment by kknee** [comment]
@kbailey-noaa ok, then we are all set with this one I think.  https://eds.ioos.us/thredds points to the new TDS.  Can you confirm and close?

**Comment by kbailey-noaa** [comment]
@kknee confirmed, but some questions before I close:
The Model Viewer "EDS THREDDS" links within the abstracts are giving FileNotFound errors.  Is this expected even though the URL didn't change? (I assume yes, but our previous conversations assumed the URL was changing to tds.eds.ioos.us, so wanted to double check).

I'd like to announce/celebrate the release of this upgraded THREDDS at some point.  Is it too soon to broadcast?  I'm flexible.

**Comment by Bobfrat** [comment]
@kbailey-noaa yes this is expected and is on my todo list (we can create a new issue for this for tracking). The previous eds.ioos.us/thredds endpoint was pointing to the old EDS TDS server. This new gold standard server has a completely different organization so all the links from OceansMap are broken at the moment. 

We're now in a situation where we have the WMS coming from the legacy EDS system but we want users to see the IOOS EDS TDS gold standard endpoints. We were previously getting the correct URLs for the old version via the EDS custom WMS GetCapabilities request. That won't work anymore so I'll have to update all the URLs for the individual layers.

**Comment by kbailey-noaa** [comment]
@Bobfrat Issue #198 covers that switch from legacy EDS to the THREDDS.  Closing this issue and transferring part of your comment over to 198.
