### ISSUE TITLE
SFBOFS layer not loading

### ISSUE THREAD

**Issue by dpsnowden** [asascience-open/IOOS-EDS#177]
I tried both Firefox and Chrome.  Other users can see the layers at the same time I was trying to use them.    It may be related to the NOAA IP addresses.  Kathy was home and could load the layer fine.  I tried three different users sitting at computers in NOAA and they all had the same "Could not load this layer" error.  

Notice that the time series from the virtual buoy will plot but the map veiw will not.

![image](https://user-images.githubusercontent.com/3603125/55637999-39529300-5794-11e9-9d56-bacb297d1072.png)

**Comment by Bobfrat** [comment]
I think its actually got something to do with the size of the image requested. I'll have the EDS team take a look. If you make your browser smaller, does the image show up?

**Comment by dpsnowden** [comment]
That seems to be the case.  See screenshot below.  Hopefully that's an easy fix.  Thanks @Bobfrat 

![image](https://user-images.githubusercontent.com/3603125/55744220-6ad09600-5a02-11e9-9439-8803a1673c6b.png)

**Comment by kbailey-noaa** [comment]
@dpsnowden Are you still having issues with this?  Can you try plotting SFBOFS water temp in [eds.ioos.us](https://eds.ioos.us/) again?
