### ISSUE TITLE
LEOFS layer issues

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#18]
Missing water level and water temp layers for LEOFS.

LEOFS sfc currents time series won't load but pop-up window shows values (and layer displays).  Loads if I go back in time one hour.
![screen shot 2016-05-25 at 7 52 54 pm](https://cloud.githubusercontent.com/assets/11823385/15559705/9bf77814-22b2-11e6-971e-75b01007f58c.png)

**Comment by kknee** [comment]
@kbailey-noaa this is the new OFS layer for Erie.  Since they stopped running the old one, we  updated the currents, but we'll have to wait for the new contract to get in the other parameters.

Regarding the TS plot, we'll take a look.

**Comment by kknee** [comment]
@kbailey-noaa the TS issues are resolved.

**Comment by kknee** [comment]
@kbailey-noaa water temp and level are now in EDS.  Should show up in the UI tomorrow.
