### ISSUE TITLE
ENC WMS endpoint change

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#181]
As of July 20, 2019 the ENC Online Web Map Service (WMS) will change (details below). The WMS is used in the NOAA ENC Viewer and provides a continuous depiction of all NOAA ENC® coverage over U.S. coastal waters and the Great Lakes. Due to this change, applications and maps that have the current link loaded and saved in them will be affected and the new link will need to be implemented by the user to ensure a seamless transition.  The new URL that will be implemented on July 20th 2019. Until this date, please continue to use the existing URL. Please feel free to contact OCS GIS Team (ocs.gis@noaa.gov) with any questions or concerns. 

Existing ENC Service URL: 
https://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/Maritime Chart Server 

New ENC Service URL (effective July 20th, 2019)
https://gis.charttools.noaa.gov/arcgis/rest/services/MCS/ENCOnline/MapServer/exts/MaritimeChartService

**Comment by Bobfrat** [comment]
Updated on dev:
http://dev.oceansmap.com/eds/

If happy we can push to production

**Comment by kbailey-noaa** [comment]
@Bobfrat Looks good! Pls push to production.

**Comment by Bobfrat** [comment]
ok all set on production now
