### ISSUE TITLE
CBIBS API not returning data

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#182]
Per May 29 email exchange, Cheryl had investigated and fixed a netCDF error but the CBIBS API is not returning data.  Kelly told Doug Wilson and CJ.  

API still not updating as of 7/15/19.

**Comment by kknee** [comment]
@kbailey-noaa we were notified that the new CBIBS API was ready for us to develop against on July 22.  We should have the layer working this week, but not sure it will be ready for prime-time for Thursday.

**Comment by kbailey-noaa** [comment]
@kknee Thanks! Will look out for it.

**Comment by kknee** [comment]
@kbailey-noaa CBIBS is back!  Stations Potomac and Stingray point are not current reporting, but you can see historical data where available.  Also - the new API doesn't seem to have the profile data that we had before, we are in contact with NCBO about that.

**Comment by kbailey-noaa** [comment]
Awesome. Thanks!
