### ISSUE TITLE
Missing abstracts

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#183]
@Bobfrat Several layers are missing abstracts.  e.g. SFBOFS water level

**Comment by Bobfrat** [comment]
This should be addressed with the transition to the new TDS/WMS services.

**Comment by kknee** [comment]
@kbailey-noaa I just sent a list of abstract to add to the EDS team to put in the DB.  Hoping to get this done tomorrow, but I will confirm.  Everything on the list was pulled from model websites, not provided directly by model PI.

**Comment by kknee** [comment]
@kbailey-noaa most abstracts added, missing a couple NWPS and Doppio and a few others that I'm not comfortable guessing at.

**Comment by kknee** [comment]
@kbailey-noaa NWPS and Doppio added, for the few others that are missing we need more info
