### ISSUE TITLE
NWPS layer names

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#186]
@Bobfrat 
All the NWPS layers appear to have a duplicate set of 3 that aren't labeled and don't load anyway.  Remove? 
e.g. Mount Holly/Philadelphia, New York/Upton CG1, etc.
Names are also inconsistent.  Some are "NOAA NWPS [region] Wave Height," others are "[Region] (NWPS Wave Height)"
Abstracts missing for all these layers.

![image](https://user-images.githubusercontent.com/11823385/62385747-e0b5bb80-b523-11e9-80fa-4590590ade2c.png)

**Comment by kknee** [comment]
@kbailey-noaa - these were parameters that came with NWPS that we probably dont' want to show (currents, winds, water levels).

@Bobfrat I removed the layers from the IOOS EDS keys (prod and dev).  Can you refresh the catalog? 

Will work on name updates next....

**Comment by kknee** [comment]
@kbailey-noaa extra layers removed and names updated, still finalizing abstracts

**Comment by kknee** [comment]
@kbailey-noaa missing abstracts are captured in #183 so suggest the layer updates noted above are ready for review and hopefully closure

**Comment by kbailey-noaa** [comment]
@kknee Looks good!
