### ISSUE TITLE
Remove LMHOFS salinity

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#189]
@kknee @Bobfrat 
From Machuan (CO-OPS):
Thanks very much for your quick work on this.  Salinity is not OFS' targeted variable in Great Lakes region, could you please don't show LMHOFS salinity on the Model Reviewer?

**Comment by kknee** [comment]
@Bobfrat I removed from EDS prod and dev keys + GLOS key (68, 1202, 1157).  Can you refresh data catalogs?

**Comment by Bobfrat** [comment]
Ok, should be all set

**Comment by kknee** [comment]
confirmed.
