### ISSUE TITLE
Add 'Not for Navigation' Message to ENC basemap

### ISSUE THREAD

**Issue by kknee** [asascience-open/IOOS-EDS#19]

**Comment by kbailey-noaa** [comment]
I saw this is in the dev version but not production yet.  It's a bit easy to miss, though - can you make the text larger or somehow that message more prominent?  Zdenka was asking about this, so wanted to make sure we implement this sooner than later.

**Comment by kknee** [comment]
@lukecampbell can you deploy the development version to production.  Also do we have any control over that text size in the lower left.

@kbailey-noaa I think we should also add it to the general disclaimer that you were working on.

**Comment by lukecampbell** [comment]
I can take a look Monday. I'm not comfortable making changes to production on Fridays.

**Comment by kknee** [comment]
@lukecampbell might as well play around with the text size on dev first then.  If that's possible?

**Comment by kknee** [comment]
this is on production.  still a bit subtle, but I think we're okay for now?  @kbailey-noaa ?

**Comment by kbailey-noaa** [comment]
This issue was called out by the Director, so should make it more obvious.  Want to avoid any risk associated with this...

**Comment by kknee** [comment]
I will check on whether we can use our system maintenance pop-up when that basemap is selected

**Comment by kknee** [comment]
@gitchrisadams did that warning pop-up ever get deployed?

**Comment by kknee** [comment]
@gitchrisadams nevermind, clearly i need to load the ENC basemap to see this ;)

@kbailey-noaa this is all set on production:

![image](https://user-images.githubusercontent.com/196868/38713163-cf41b9f6-3e9d-11e8-9328-e2c2b547ed4b.png)
