### ISSUE TITLE
CNAPS plot units

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#190]
@kknee @Bobfrat 
I set units to "US" and the SECOORA CNAPS water temp plot still shows deg C.  Yet the legend shows deg F.

![image](https://user-images.githubusercontent.com/11823385/63882184-7f0c3400-c99f-11e9-908b-d9b75ddb606e.png)

**Comment by Bobfrat** [comment]
Fixed on dev (along with the hurricane layer order issue you mentioned in email) I'll do some testing tonight and push to production if ok.
http://dev.oceansmap.com/eds/
