### ISSUE TITLE
Missing CNAPS / HFR data

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#193]
@Bobfrat @kknee 

Per the image:

CNAPS hasn't updated since 9/4 20:00.  Broken data feed?

HFR currents shows data in the pane but won't plot. Virtual station is within HFR vector 'domain.'  This is for 9/4 (yesterday) so not a real-time data issue.  

![image](https://user-images.githubusercontent.com/11823385/64352343-dfb3f600-cfc9-11e9-9fc8-00d9584b31bf.png)

**Comment by kknee** [comment]
@kbailey-noaa we'll take a look at CNAPS.  

Re HFR - that same source is returning plots for the vectors off NJ, but not further south.  @Bobfrat  -here's what looks like a valid GFI for a request off Charleston: 

https://eds.ioos.us/api/wms?url=http%3A%2F%2Fcoastmap.com%2Fecop%2Fwms.aspx&SERVICE=WMS&REQUEST=GetFeatureInfo&VERSION=1.1.1&LAYERS=HFRADAR_USEGCCUR_CURRENTS&STYLES=CURRENTS_RAMP-Jet-false-2-true-0-2.25&FORMAT=image%2Fpng&TRANSPARENT=true&COLORSCALERANGE=0%2C2.25&EXCEPTIONS=application%2Fvnd.ogc.se_xml&WIDTH=1231&HEIGHT=390&SRS=EPSG%3A3857&BBOX=-12398469.796142846%2C2487972.5101375445%2C-6376454.959723522%2C4395840.736135542&QUERY_LAYERS=HFRADAR_USEGCCUR_CURRENTS&INFO_FORMAT=text%2Fxml&X=748.4534567980068&Y=98.58296486701869&_LAT=33.12407143384424&_LON=-78.46765889340014&time=2019-08-31T13%3A00%3A00Z%2F2019-09-08T13%3A00%3A00Z&map_time=2019-09-04T13%3A00%3A00Z&unit_system=default

**Comment by kknee** [comment]
@kbailey-noaa CNAPS source only has files through yesterday.

**Comment by kknee** [comment]
@kbailey-noaa CNAP appears to be fine. 

@Bobfrat looking at the HFR issue

**Comment by Bobfrat** [comment]
HFR timeseries has been updated on dev: http://dev.oceansmap.com/eds/

**Comment by kbailey-noaa** [comment]
@Bobfrat looks like HFR were updating on dev but stopped ~12/20, then there is 1 data point for today 12/23 and 1 from yesterday.  Looking at the small swath off the SC coast.  Other HFR areas (outer banks and north) seem fine though.  If this is just a source HFR dissemination problem then consider this resolved.  
CNAPS is updating.

**Comment by kknee** [comment]
@kbailey-noaa I am following up with the HFR experts, but I think that missing patch is a source problem.

We have resolved the issue related to this ticket, which was that virtual buoys were working inconsistently for HFR data so I am going to close.

**Comment by kknee** [comment]
@kbailey-noaa to conclude on the SC HFR, it went offline entirely on Dec 26th: 

https://hfrnet.ucsd.edu/diagnostics/?p=sta&sta=GTN&aff=SC&t=0
