### ISSUE TITLE
Doppio currents TS won't plot

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#199]
When I drop a virtual station in the Doppio currents grid I get an error even though the vectors display in the map.  Data are recent and I adjusted the time slider but get the same error.  No issue with Doppio temp or salinity, though.

![image](https://user-images.githubusercontent.com/11823385/66322428-198d5a80-e8f0-11e9-91b0-bc460dde15d0.png)

**Comment by kknee** [comment]
@kbailey-noaa we are taking a look

**Comment by Bobfrat** [comment]
I've got a fix on http://dev.oceansmap.com/eds/. Just need to do some more testing on the other layers as well then I can push to prod.

**Comment by kbailey-noaa** [comment]
@Bobfrat Let's wait til early next week (or maybe that's when you'd be able to do it anyway!).  I hope CO-OPS people try out the tool after my demo, so don't want to disrupt anything.

**Comment by Bobfrat** [comment]
@kbailey-noaa I pushed this update to production, please have a look. I'm doing some testing as well.

**Comment by kbailey-noaa** [comment]
Looks good!
