### ISSUE TITLE
TS unavailable for half RENCI ADCIRC domain

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#202]
@kknee @Bobfrat 
Per Chris Barker, and I just verified.
Clicking in the grid for SECOORA RENCI ADCIRC currents anywhere south of the NC/SC border won't produce a time-series plot.  If I click anywhere north of that border I can plot the TS.  Yet, going out eastward just beyond the gulf stream, I also can't get a TS plot to show up as well, regardless of how far north or south I am. (e.g. near Bermuda).

**Comment by Bobfrat** [comment]
ah yes looks like a metadata issue on our end. If you mouse over the layer you see the outline of the model extents that we're getting from the GetCapabilities service. That doesnt match with the actual extents. The virtual station uses that bounding box to determine whether it should even try to fetch the data.

**Comment by kknee** [comment]
@Bobfrat so the fact that it doesn't try is an OceansMap thing, nothing to do with data not coming back from EDS if the GFI coordinates are outside the bbox? 

in this case, not sure that the small bbox is a metadata issue, pretty sure that the bbox extends control data availability in SAROPS, and the CG may not want SAR controllers using outside the NC coast.  Will try to confirm.

**Comment by kknee** [comment]
@Bobfrat to ignore the bbox extents for GFI requests.  we'll test performance when this is done

**Comment by Bobfrat** [comment]
Deployed to dev (may require a browser hard refresh)
http://dev.oceansmap.com/eds/

**Comment by kknee** [comment]
@Bobfrat this approach displays all the GFI results, which is expected, but it also trys to plot them all, which throws an error since so many don't overlap with the GFI coordinates.

If I turn all but the layers of interest off, the plot works, and when I turn them all back on, it still works, but the intial view is this error: 

![image](https://user-images.githubusercontent.com/196868/71027828-078f1b80-20da-11ea-8207-8f6e403c1615.png)

**Comment by Bobfrat** [comment]
ok so this behavior is ok but need to make sure plots don't get hung up with bad time series requests?

**Comment by kknee** [comment]
let's see if we can fix this on the EDS side; if we updated the bbox in the getcaps would that fix it?

**Comment by Bobfrat** [comment]
yes thats right

**Comment by kknee** [comment]
okay, eds team is on this, slightly different solution than above.  doing to create a duplicate WMS layer that we can hit

**Comment by kknee** [comment]
@kbailey-noaa this one is all set on production, just needed to add a WMS layer with the entire model domain represented by the bbox.
