### ISSUE TITLE
Validate tool units

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#203]
I have the units set to "US" and the validate tool didn't convert the modeled (CBOFS) water temps to deg F:

![image](https://user-images.githubusercontent.com/11823385/66343341-76513b00-e919-11e9-9a0a-73f0fb4d934f.png)

**Comment by Bobfrat** [comment]
I've got this fixed on dev.
dev.oceansmap.com/eds
![Screen Shot 2019-11-14 at 3 20 04 PM](https://user-images.githubusercontent.com/5702672/68893096-67b52b00-06f2-11ea-9cde-1e39e8b4b9f8.png)

**Comment by kbailey-noaa** [comment]
I tried it in dev and it works for me too.  I'll close this once moved to production

**Comment by kbailey-noaa** [comment]
@kknee
@Bobfrat  Still not seeing the fix on production:

![image](https://user-images.githubusercontent.com/11823385/71379851-e9726100-259a-11ea-8f29-fd7bc135f787.png)

**Comment by Bobfrat** [comment]
will push to prod shortly

**Comment by kbailey-noaa** [comment]
@Bobfrat I keep getting this error when I try to use the Validate tool in prod: Server returned an invalid XML document and could not be parsed

**Comment by Bobfrat** [comment]
seems to be working now when looking at the past 7 days but not when looking at last 30 days. Must be an issue with one of the forecast datasets ingested in EDS last week.  I'll have a look

**Comment by kbailey-noaa** [comment]
@Bobfrat I see it working now too.  I think there was a CBOFS water temp data gap somewhere between 12/23 and 12/27 that might explain the problem.  Closing.
