### ISSUE TITLE
MARACOOS HFR 1 and 2 km 

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#204]
...layers are not loading. Tried different date/times.  The 6 km layer loads, though.

**Comment by kknee** [comment]
@kbailey-noaa need to follow up on what's going on with the 1km and 2km sources, there is no recent data for them

**Comment by kknee** [comment]
@Bobfrat these layers are no longer collected by EDS.  I removed from the EDS key, can you refresh the catalog?

**Comment by Bobfrat** [comment]
all set, those layers have been removed
