### ISSUE TITLE
Navy HYCOM global layers

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#205]
...won't load (except currents).  Salinity, water level, water temp give an "error drawing this layer".  Tried different timestamps.

**Comment by kbailey-noaa** [comment]
Actually, the water level, salinity and water temp data won't display in the map but I was able to get the time-series data to show up in the plot for a virtual station location. Only GOMOFS shows up in the map in this image but all TS data plot:

![image](https://user-images.githubusercontent.com/11823385/66345433-14470480-e91e-11e9-87a0-2383de03aa07.png)

**Comment by kknee** [comment]
@kbailey-noaa they are all drawing in the map for me. Can you give it another try?

**Comment by kbailey-noaa** [comment]
@kknee They're back!  Did you have to fix anything, or was it just a source hiccup?  Just curious

**Comment by kknee** [comment]
@kbailey-noaa I check with the EDS team if they noticed an issue independent of us and fixed it.  I did not request any fixes...
