### ISSUE TITLE
IOOS RA domains

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#209]
Can you please update the RA Boundaries layer with the attached?  Hopefully that's what you need...?  The GLOS layer will change to just outline the Great Lakes, rather than show the watershed.  

[RA Boundaries 2017.gdb.zip](https://github.com/asascience-open/IOOS-EDS/files/3718162/RA.Boundaries.2017.gdb.zip)

**Comment by kbailey-noaa** [comment]
@kknee @Bobfrat Is it possible to update the layer next week?  I'm trying to get the boundaries published through NOAA, and the NOAA geoplatform where they're hosted can't be the only source.  They're willing to point to the Model Viewer as the 'authoritative source' for IOOS.

**Comment by Bobfrat** [comment]
@kbailey-noaa we got the ball rolling so that should be do-able. I'll keep you updated as we progress

**Comment by kbailey-noaa** [comment]
@Bobfrat Awesome, thanks!

**Comment by Bobfrat** [comment]
@kbailey-noaa service has been updated. Can you verify this looks as expected?
![Screen Shot 2019-10-17 at 12 09 26 PM](https://user-images.githubusercontent.com/5702672/67027113-fd02d680-f0d6-11e9-96d0-89efa29ec2ad.png)

**Comment by kbailey-noaa** [comment]
@Bobfrat Looks good!
