### ISSUE TITLE
NOAA Coral Reef Watch layers

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#211]
User request from the NOAA Coral Reef Watch (Jacqueline De La Cour) to add several layers to the IOOS Model Viewer:

1. NOAA Coral Reef Watch's [near real-time daily global 5km satellite coral bleaching heat stress product data](https://coralreefwatch.noaa.gov/product/5km/index.php) (i.e., our [sea surface temperature [SST]](https://coralreefwatch.noaa.gov/product/5km/index_5km_sst.php), [SST Anomaly](https://coralreefwatch.noaa.gov/product/5km/index_5km_ssta.php), [Coral Bleaching HotSpot](https://coralreefwatch.noaa.gov/product/5km/index_5km_hs.php), [Degree Heating Week](https://coralreefwatch.noaa.gov/product/5km/index_5km_dhw.php), [Bleaching Alert Area 7-Day Maximum](https://coralreefwatch.noaa.gov/product/5km/index_5km_baa_max_r07d.php), and [SST Trend](https://coralreefwatch.noaa.gov/product/5km/index_5km_ssttrend_7d.php) products from 1985 to the present) incorporated into the viewer.

The modeled [Four-Month Coral Bleaching Outlook product](https://coralreefwatch.noaa.gov/satellite/bleachingoutlook_cfs/index.php) (which is updated weekly) added to the viewer.

---
There is a lot here.  I found an [overview](https://coralreefwatch.noaa.gov/satellite/product_overview.php) page and (perhaps more importantly) a [data files](https://coralreefwatch.noaa.gov/satellite/hdf/index.php) page, which look useful.  Funny - the THREDDS link goes to the PacIOOS THREDDS, so they appear to have some kind of partnership with them.  

A thought:  These are observations...  I'm not sure this is something that needs to be integrated in our THREDDS.  I wonder if they have WMS enabled (or if not, then PacIOOS probably does) and if so then we could just point the Model Viewer to their (or PacIOOS') WMS service without integrating into our THREDDS.  But I'm not clear on whether this would reduce any functional capabilities for that layer in the Model Viewer - will the user still be able to click within the layer to get the time-series at the virtual station location? Or does the data have to be in EDS for that functionality to exist?  ....or are these layers just images?  Unclear if they're even interactive.  I assumed they were since there are .nc files.
I suppose I have the same question for the ice observations in issue #210

**Comment by kbailey-noaa** [comment]
@kknee @Bobfrat 
Update based on our call today:  Will point the Viewer to the PacIOOS WMS service (assuming it's available) and see how it looks in the Viewer.  May want to integrate into the EDS but will determine that later, based on how the layers look. 

Will need to provide abstracts - can just take the wording from the Coral Reef Watch pages - and will likely tuck these layers under a new TOC category.  Name TBD.  I'm leaning towards calling it "NOAA Coral Reef Watch" and then simply bundle the layers underneath without having to include attribution in the layer name or worry about geography.  That first layer name ("near real-time daily global 5 km satellite coral bleaching heat stress") is super long though.  May need to involve Jacquie on an adequate name.

**Comment by kbailey-noaa** [comment]
@Bobfrat As requested:
From the [PaciOOS THREDDS](http://oos.soest.hawaii.edu/thredds/idd/satellite.html?dataset=dhw_5km) would like to see basically everything in there minus sea-ice-area-fraction. 
Create new TOC cateogry named "NOAA Coral Reef Watch."
Layers I'd like to see + suggested TOC names are:

1.  CRW_SST (Celsius) = nighttime sea surface temperature = sea_surface_temperature
Name in TOC:  Sea Surface Temperature
Palette: Jet

2.  CRW_BAA (1) = coral bleaching alert area (7-day max) = coral_bleaching_alert_area
Name in TOC: Alert Area (7-day max)
Palette: Hot, but in reverse so that yellow is lowest and red is highest.

3.  CRW_DHW (Celsius weeks) = coral bleaching degree heating week = coral_bleaching_degree_heating_week
Name in TOC: Degree Heating Week
Palette:  Spring but in reverse so that purple is highest.

4.  CRW_HOTSPOT (Celsius) = coral bleaching hot spots = coral_bleaching_hot_spots
Name in TOC: Coral Bleaching Hotspot
Palette:

5.  CRW_SSTANOMALY (Celsius) = nighttime sea surface temperature anomaly = sea_surface_temperature_anomaly
Name in TOC: Sea Surface Temperature Anomaly
Palette: 

ncWMS default palette:  Ran out of time today, but will update rest of this entry with palettes.

**Comment by kbailey-noaa** [comment]
@Bobfrat 
Abstracts + Data Access links:

1. Alert Area: 
"The NOAA Coral Reef Watch (CRW) experimental daily global 5km (0.05 degree exactly) satellite coral bleaching heat stress monitoring product suite spans January 1, 1985 to present and is based on CRW's Version 3.1 daily global 5km satellite sea surface temperature (SST) data product known as 'CoralTemp.' This Version 3.1 5km product suite comprises the core of CRW's Decision Support System (DSS) for coral reef management, providing service at or near reef-scales, allowing direct monitoring of 95% of global coral reefs and significantly reducing data gaps caused by cloud cover. Current CRW near real-time 5km global products include SST, SST Anomaly, Coral Bleaching HotSpot, Degree Heating Week (DHW), a 7-day maximum Bleaching Alert Area, and a 7-day SST Trend. 
The 7-day maximum Bleaching Alert Area is a composite product, updated daily, that shows the maximum stress level that a satellite pixel has experienced during the most recent 7 consecutive days. Data and images are dated on the last day of the 7-day period.  Notably, it is compatible with CRW's heritage operational 50km twice-weekly Bleaching Alert Area product, as the 50km Bleaching Alert Area is based on a half-week (3 or 4 days) composite of 50km SSTs (but with much less SST variability due to its much coarser spatial resolution).
Source: https://coralreefwatch.noaa.gov/"

Data Access:  PacIOOS THREDDS [http://oos.soest.hawaii.edu/thredds/idd/satellite.html?dataset=dhw_5km]

2. Coral Bleaching Hotspot, 3. Degree Heating Week, 4. SST anomaly, 5. SST -- Use this abstract:
"The NOAA Coral Reef Watch (CRW) experimental daily global 5km (0.05 degree exactly) satellite coral bleaching heat stress monitoring product suite spans January 1, 1985 to present and is based on CRW's Version 3.1 daily global 5km satellite sea surface temperature (SST) data product known as 'CoralTemp.' This Version 3.1 5km product suite comprises the core of CRW's Decision Support System (DSS) for coral reef management, providing service at or near reef-scales, allowing direct monitoring of 95% of global coral reefs and significantly reducing data gaps caused by cloud cover. Current CRW near real-time 5km global products include SST, SST Anomaly, Coral Bleaching HotSpot, Degree Heating Week (DHW), a 7-day maximum Bleaching Alert Area, and a 7-day SST Trend.  

Source: https://coralreefwatch.noaa.gov/"

Data Access:  PacIOOS THREDDS [http://oos.soest.hawaii.edu/thredds/idd/satellite.html?dataset=dhw_5km]

**Comment by Bobfrat** [comment]
@kbailey-noaa soudns good. BTW, the other layers are in dev now as well. At the bottom of the TOC is a new category for Coral Reef Watch
http://dev.oceansmap.com/eds/

**Comment by kbailey-noaa** [comment]
@Bobfrat I saw!  Awesome.  Can I share this Dev site with the CRW group, or would you prefer I refrain?
Changed my mind on the Alert Area name, now that I see it.  Can you change it to "**Bleaching** Alert Area (7-day max)?"

FYI the other 2 products they requested are available via FTP (.nc files), organized in yearly folders.
SST Trend:
ftp://ftp.star.nesdis.noaa.gov/pub/sod/mecb/crw/data/5km/v3.1/nc/v1.0/daily/sst-trend-7d/
and 
4 month outlook: ftp://ftp.star.nesdis.noaa.gov/pub/sod/mecb/crw/data/outlook/v5/nc/v1/outlook/

But looking at 4 month outlook product (and FTP files) this seems more complicated.  Each week the FTP site updates with 9 .nc files, for probabilities ranging from 10 - 100% in increments of 10%.  Since their CRW website only shows the 60% and 90% probability maps we could just only show those.  And in the abstract we could state that the data shown are for the 4 month outlook period beginning at the 'Valid Time' shown in the TOC.  We could name the layers "4 Month Bleaching Outlook (60%)" and "...(90%)."  

LMK if those last 2 products are time-consuming.  If so we can hold off.

**Comment by Bobfrat** [comment]
Feel free to share the dev link, just let them know that the site can be unstable because its dev.

Noted on the ToC names and abstracts, I'll get that updated

And I'll have a look at the other products to get a feel for the level of effort.

**Comment by kbailey-noaa** [comment]
@Bobfrat Feedback from the CRW (Gang Liu):

 Bleaching Alert Area layer:
- [ ] Remove remove "7-day max" in the product name so that it is same as all other products (SST, SSTA, HS, DHW).
- [ ] Remove "a 7-day maximum" in the product description.

**Comment by kbailey-noaa** [comment]
@Bobfrat - CRW abstracts
[IOOS_EDS_Model_Viewer_product_descriptions_20191113.docx](https://github.com/asascience-open/IOOS-EDS/files/3843570/IOOS_EDS_Model_Viewer_product_descriptions_20191113.docx)

**Comment by Bobfrat** [comment]
updated on dev.oceansmap.com/eds

**Comment by kbailey-noaa** [comment]
@Bobfrat 
1) I'm running into odd behavior with the Bleaching Alert Area layer.  Sometimes I turn it on then move the map while it's still loading and it then it doesn't load.  But if I nudge the map a little with the hand icon I get little glimpses of the layer but then it disappears.  

2) Looking at the legend and abstract for Bleaching Alert Area where the values are defined, I'm a little confused.  I thought the data are whole #s (0 - 5) to signify alert levels, but the legend and abstract both imply there can be decimal values.  I suspect that's not the case.. Can you confirm?
If they are in fact whole values, then could you change the legend for the Bleaching Alert Area so it distinctly shows what 1 - 5 mean?  i.e. to match the legend (more or less) here: https://coralreefwatch.noaa.gov/data/5km/v3.1/current/daily/gif/cur_coraltemp5km_max_r07d_baa_large.gif
Or at least could you not show decimals?
But we don't need to show 'no data' or 'no stress.'  We'd only display in the legend: 1 = Watch, 2 = Warning, 3 = Alert Level 1, and 4 = Alert Level 2 (hopefully I got that right).  

Also, why is there "(1)" in the legend title?

3) The default color scale range in settings for Coral Bleaching Hotspot is -20 to 20.  Can you update that to 0 - 5?  

4) This is super picky but for Sea Surface Temperature, the legend 'title' includes underscores but the other legend titles do not.

...all that said, I'm not realizing the legend might be part of the WMS service itself. If so then a lot of this is moot!

**Comment by Bobfrat** [comment]
So, we're sort of at the mercy of the PacIOOS WMS server here. We'll have to start ingesting and leveraging our own WMS services if we want some custom updates to things like the legend. Let me know if you want us to proceed with that. It would need to be part of the 2020 source integration work to get into the new TDS server we're working on.

**Comment by kbailey-noaa** [comment]
@Bobfrat What is the status of this effort?  Re: my last comment (and your response) I recommend just going with the easiest solution and leaving the legend alone / go with what PacIOOS WMS server provides.  If the CRW folks have concerns with that then we can add an issue to integrate into the new TDS.  Ideally it would be best to show something now in prod though.

**Comment by Bobfrat** [comment]
@kbailey-noaa i have been working on updating the palettes (and legends), trying to implement the same palettes used on the NOAA site. Things stalled a bit recently but I'm currently working on the Degree Heating Week palette. The last comments from Gang are below:

> I see some difference between the display in the viewer and the one posted at the ftp site. I carefully checked some pixel values and see that the display in the Viewer doesn't show some value slightly greater than 8 (such as 8.1) in red but in orage. Please see the two screenshots attached. Most of the discrepancy in the lightest red (that I checked; I didn't check other colors) is caused by showing low 8.xx in orange instead of red in the viewer's display.

**Comment by kbailey-noaa** [comment]
@Bobfrat (cc @kknee )   Gang's latest email said "It is very very close to getting Degree Heating Week (DHW) color scale done, just some very small changes I assume. HotSpot, SST and SSTA should follow the exact suite of DHW once DHW is done. We are almost at the finishing line.  After I sent the last comment on DHW on Jan 17th, I haven't heard from Bob, assuming Bob has been tied by other tasks. I will check with Bob on the status."

Are these actually "small changes?" What is the level of effort required / how much time? I don't want to continue focusing your time on this but if it's that close then might as well finish.  If it's still a lot of work remaining, then I want to put a halt on Gang's requests.

**Comment by Bobfrat** [comment]
@kbailey-noaa i have a few more small things to try and if that doesn't work I'll call it quits.

**Comment by kbailey-noaa** [comment]
@Bobfrat Ok, thanks!

**Comment by kbailey-noaa** [comment]
@Bobfrat Gang's latest email indicated we're done with the CRW layers.  Can we move those into production?

**Comment by Bobfrat** [comment]
Yes we can!

**Comment by Bobfrat** [comment]
@kbailey-noaa all set on prod now.
