### ISSUE TITLE
Add CO-OPS tide predictions

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#24]
Add a tide predictions layer from CO-OPS.  (This can be one of several tide prediction options, presented in the TOC).  
Values should be referenced to MLLW.  This should be harvested from http://opendap.co-ops.nos.noaa.gov/ioos-dif-sos/#.  The parameter name is "sea surface amplitude due to equilibrium ocean tide."  However, please display the parameter name as "tide prediction."  Or "astronomical tide prediction."

**Comment by kbailey-noaa** [comment]
Recommend combining this with issue #62 (explore use of API).

**Comment by kknee** [comment]
@kbailey-noaa these have been in for some time, we need to change the display name before closing the issue.  If we change to the API, we'll pull them from there instead, so not sure we need to combine the issues.

**Comment by kknee** [comment]
@kbailey-noaa I lost track of where we landed for display name.  We had homogenized to the following some time ago:

![image](https://user-images.githubusercontent.com/196868/38908930-5ee4f9ba-4290-11e8-8112-2790f7cd26eb.png)

**Comment by kbailey-noaa** [comment]
Looks good. I don't see that in dev, so not sure if all the other github updates were reflected on dev yet?

**Comment by kbailey-noaa** [comment]
Oh I do see it.  Closing.
