### ISSUE TITLE
Proper RA attribution of obs

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#36]
RAs provided feedback that they want to see their stations appropriately credited to them, not NDBC.  For example, "NDBC" station 46108 in Cook Inlet, AK is actually an AOOS buoy.  (Although, I don't see that station listed anywhere on their THREDDS server, so that's strange!: http://dods.ndbc.noaa.gov/thredds/catalog/data/ocean/catalog.html)

The Environmental Sensor Map is also tackling this issue, though they changed their retrieval services to point to the RAs' SOS instead of NDBC.  However, they are including more than just buoys.  It's possible we might need to look at their approach to solve this.  

FYI - the NDBC station page lays out who owns what, though I'm not sure if their SOS has any metadata that would provide distinction in ownership.  http://www.ndbc.noaa.gov/to_station.shtml

Re: how to display RA observations, rather than list 11 different RAs, I recommend we simply create a layer called "Regional Associations" and have that toggle on/off all RAs' observations that are separated from the current NDBC and Partners list.

**Comment by kknee** [comment]
so the "& Partner Stations" is not going to fly...

First step here is to look into the level of effort, I'm afraid it's not going to be small.

**Comment by kknee** [comment]
@kbailey-noaa for the interim, we're pulling attribution info from NDBC and have added it to the station pop-ups 'Attribution' sub title.  We've also added the location description from NDBC to the pop-up title, here's a NERACOOS example + the 46108 AOOS example: 

![image](https://cloud.githubusercontent.com/assets/196868/19577050/8e06604e-96e3-11e6-9a53-7a78cf7f7020.png)

![image](https://cloud.githubusercontent.com/assets/196868/19577091/b4a798a8-96e3-11e6-89e0-be40963cac37.png)

**Comment by kbailey-noaa** [comment]
We don't need to spell out the RA acronym.  Also, we should be consistent with the IOOS Environmental Sensor Map in terms of how we show attribution.  In the AOOS example, can you put AOOS as a top line (not in bold font), and then followed by the rest of the station name information as shown?  Do not include the term "attribution." (No need).  

Here is the Sensor Map display:
![axiom_attribution](https://cloud.githubusercontent.com/assets/11823385/21723401/488055fe-d3fe-11e6-9ba6-f50c873abeda.PNG)

**Comment by kbailey-noaa** [comment]
I'll write Frank and push for an acronym change at NDBC.  Pulling back the request about ordering of station name and RA name.  Agreed to put attribution in bold.

**Comment by kknee** [comment]
pop-ups have been updated to remove the 'Attribution' label and make attribution bold:

![image](https://cloud.githubusercontent.com/assets/196868/26005490/343430a4-3707-11e7-800b-3f2a4511a868.png)

**Comment by kbailey-noaa** [comment]
Looks good!
