### ISSUE TITLE
Generate user statistics for the IOOS Model Viewer

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#42]
This is a placeholder to explore how to generate/report out (internally) user statistics.  Need to gain a better understanding of the level of use plus who specifically is using the tool.

**Comment by kknee** [comment]
@kbailey-noaa I sent you an analytics report - let me know what you think

**Comment by kknee** [comment]
Google analytics added and reviewd by @kbailey-noaa 

this issue is now superceded by #50

**Comment by kbailey-noaa** [comment]
We at IOOS determined we want to  pursue archiving and submitting web logs to NOS for each of our products, eds.ioos.us.  I would still like to see Google analytics reports, but this is separate.  Luke is familiar with this/working on this already for Catalog.  
Details of this request are described in https://github.com/ioos/catalog-ckan/issues/133, and here is some info from that issue, which would apply to eds.ioos.us as well:

The key things we need to request for logs are:

- Use Apache 'combined' log format, or similar (I included the info from NOS log info site below)
- Log file name includes domain name (eds.ioos.us, data.ioos.us, etc), plus year/month string
- Monthly logfile rotation

In order to get the most value from these logs, servers should be configured to log the following W3C tokens (or their NCSA or IIS equivalents):

DATE
TIME: time can be either UTC or local, as long as it doesn't change
CS-URI: the URI portion of a request (the portion after the host name)
C-IP: client (visitor) IP address
BYTES: bytes sent to visitor.
SC-STATUS: status code (i.e., 200, 404, etc.)
CS(REFERER): site and page visitor clicked on to link to your page
CS(USER-AGENT): browser or robot name and version
CS-USERNAME: of use for sites requiring authentication
TIME-TAKEN: time required to send response
CS(HOST): name of host site requested by the visitor
CS-URI-QUERY: CGI (Common Gateway Interface) arguments
CS-METHOD: request header (GET, PUT, etc.)
CS-VERSION: HTTP protocol version number.

**Comment by kbailey-noaa** [comment]
Per Micah, it looks like this might not be a good avenue to pursue.  Closing.
