### ISSUE TITLE
Add feedback option

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#46]
Add feedback link to the About menu.  (High priority)

**Comment by kbailey-noaa** [comment]
Relabel as "feedback."

**Comment by kbailey-noaa** [comment]
Discussed further with Derrick, re: the specific requirement.  The requirement is that we want to actively coax users into providing feedback about the product - similar to the NANOOS NVS (
http://nvs.nanoos.org/ContactUs) - as opposed to simply providing a mechanism for users to contact us.  We are concerned the position of the contact us link is not visible enough to encourage feedback.  We want to take the 'contact us' a step further.
Looking at http://dev.oceansmap.com/eds/ -- we'd like to include a tab/link next to the 'map' and 'tools' buttons called "feedback" that would lead to a page like this - http://nvs.nanoos.org/ContactUs - where we can include a sentence at the top re: users' ideas for improving EDS, e.g. datasets they want to see.
I recommend we don't make name/email/phone required fields (if we provide them at all).  

Thoughts?

**Comment by kknee** [comment]
Added button and form, but want to make some tweaks to the feedback form before closing

![image](https://cloud.githubusercontent.com/assets/196868/25978151/93751c1e-368e-11e7-8e35-fa9949ecdc6b.png)

**Comment by kknee** [comment]
updated form to allow users to submit contact info (but not require it):

![image](https://cloud.githubusercontent.com/assets/196868/26024395/5cb0aeda-379e-11e7-9fde-ba0729ef5aca.png)

**Comment by kbailey-noaa** [comment]
Looks good.  Can you change it to "Please provide us with some feedback to help us improve this product."?

**Comment by kknee** [comment]
@kbailey-noaa  -title changed

**Comment by kbailey-noaa** [comment]
Looks good!
