### ISSUE TITLE
Depth profiles

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#47]
Add ability/option to plot vertical profiles.  (Low priority)

**Comment by kbailey-noaa** [comment]
@kknee Is there a status for this?

**Comment by kknee** [comment]
@kbailey-noaa it will come after the refactor that we're working on

**Comment by dpsnowden** [comment]
@kknee What is the refactor and where is it planned?  Can you list an issue in the oceansmap repo that we can use for tracking?

**Comment by kbailey-noaa** [comment]
@kknee I just plotted DBOFS time-series and noticed there is a profile plot showing change over depth!  This is exciting.  Is this meant for my review? I'm looking at production so it appears it's already been implemented.

**Comment by kknee** [comment]
by all means, please review and provide comments!  I've already asked that Bob look into plot colors.

**Comment by kbailey-noaa** [comment]
Ok.  I'm going to pass this onto a few CO-OPS people too to request their feedback.

**Comment by kbailey-noaa** [comment]
I tried NOAA Great Lakes 3D LHOFS and the plot was very hard to see.  The currents are all around the same direction and don't vary much, so the data points are clustered in one small part of the plot.
![depth_plot](https://cloud.githubusercontent.com/assets/11823385/26680514/b7b25122-46a7-11e7-9eb4-d549e515e748.PNG)
Similar issue with Lake Ontario, and almost looks like only one depth is populating the profile plot (-112):
![depth_plot2](https://cloud.githubusercontent.com/assets/11823385/26680589/065d4e6c-46a8-11e7-82b7-e47e0df88215.PNG)

**Comment by kbailey-noaa** [comment]
OFS layers show depth units (y-axis) in meters, but the depths are sigmas...  Is the depth actually calculated/converted to meters for these plots?

![screen shot 2017-06-03 at 11 17 30 am](https://cloud.githubusercontent.com/assets/11823385/26754734/4dc2b15a-484e-11e7-98bc-72390327f660.png)

**Comment by kknee** [comment]
@Bobfrat looks like depth profile date stamp defaults to 2 June, need to update - this is not happening on dev, only on production

**Comment by kknee** [comment]
user feedback:

One buoy I set happened to be just about exactly 10m depth, and the profile showed it to 10m.  However, when I clicked the "stats view" the axis changed from 0-10 to 0-20, and it was hard to see the profile.  Even when I closed the stats view, it didn't revert back.  Note that I tried this with a shallower station, and it did not have the issue.

**Comment by Bobfrat** [comment]
@kbailey-noaa the NOAA Great Lakes 3D OFS profile plots are working now. The depths you see on the plots have been converted from sigma layer to meters.

**Comment by kbailey-noaa** [comment]
I think everything looks good here.  Closing this.
