### ISSUE TITLE
Provide WMS

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#49]
Enable WMS access - to be discussed further.  (High priority)

**Comment by kbailey-noaa** [comment]
Per the SOW, some more detail:  
Public data access via WMS, applying UGRID/SGRID conventions and enabling sciWMS where applicable.  Can EDS handle the load?

**Comment by kbailey-noaa** [comment]
@kknee I wanted to revisit this.  At this point I don't believe sci-WMS is available so am looking for an udpate on this --  (http://data.oceansmap.com/thredds/catalog/EDS/FVCOM_MAINE/catalog.html?dataset=EDS/FVCOM_MAINE/fvcom_maine20171005.nc)

**Comment by kbailey-noaa** [comment]
@kknee Any update on this?

**Comment by kknee** [comment]
@kbailey-noaa starting to populate them, but have not tested yet.

**Comment by kknee** [comment]
http://data.oceansmap.com/thredds/EDS/EDS.html?dataset=EDS.NOS_CBOFS_3D
