### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#50]
Add Kbailey to automated email list for the googel analytics report.

Add option to see which datasets (layers) are accessed most.  Don't need to see stats for all layers, but top 5 or 10 would suffice. (Depending on level of effort - lower priority).

**Comment by kbailey-noaa** [comment]
@kknee can you please add this email group to the distribution list? ioos_ops@noaa.gov

**Comment by DanielJMaher** [comment]
@kknee This should be all set.  June 1 is the next report.
