### ISSUE TITLE
Explore tool: Station list

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#51]
Using the explore tool in http://dev.oceansmap.com/eds/# to plot winds for an observing station and a model. 

1) "Station list" name is misleading since it contains models as well.

2) Station list needs to identify observations vs models.  Perhaps 2 dropdown menus makes more sense, one for obs and one for models?

3) If I want to unselect a station in the station list, I have to find it by scrolling through the entire list, which is frustrating/timely.  Recommend selected stations are more visible/easy to turn off.

**Comment by kknee** [comment]
1. Updated "Station List" to "Available Stations/Models"
2. Added 'Station' or 'Model' tag to each entry in the list
3. Added 'Deselect All' button at the top of the list

**Comment by kknee** [comment]
@kbailey-noaa can this be closed?

**Comment by kbailey-noaa** [comment]
Yes, looks good.
