### ISSUE TITLE
Explore tool:  Plots

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#53]
Using http://dev.oceansmap.com/eds/# to plot a single station:

1) Need to include attribution on these plots, in the title.

2) Need to provide an explanation of how to read the plots (particularly for the wind roses).  Perhaps in the TOC through a popup (? icon) or text underneath each plot type (though that could clutter the TOC...

**Comment by kknee** [comment]
1. As discussed, attribution added to lower left of graph, which allows us to include attribution of mutliple entities if the comparison option is chosen:

![image](https://cloud.githubusercontent.com/assets/196868/25978295/5857c61c-368f-11e7-916c-ce5219698718.png)

**Comment by kbailey-noaa** [comment]
Looks good.

**Comment by kknee** [comment]
@kbailey-noaa for #2, added popups:

![image](https://cloud.githubusercontent.com/assets/196868/26586697/01340d08-451e-11e7-814e-07a152bf4827.png)

**Comment by kbailey-noaa** [comment]
Looks good.
