### ISSUE TITLE
Units not applied to water level layer

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#54]
In http://dev.oceansmap.com/eds/#:

I selected units = US, and chose DBOFS water level.  In the legend tab, the layer indicates it's loading (spinning wheel) but never updates.  

I turned on Global (HYCOM Navy) water level and it loads but remains in metric units.

**Comment by kknee** [comment]
@kbailey-noaa this is fixed on dev
