### ISSUE TITLE
OTPS tidal model layer

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#55]
In http://dev.oceansmap.com/eds/#:
If I select any water level layer, and drop a virtual buoy, there is another layer that appears to always be turned on:  Water Level @ OTPS Tidal Model.  However it isn't an option in the TOC.

![otpswl_missing](https://cloud.githubusercontent.com/assets/11823385/22377402/bb449d52-e47f-11e6-9db7-85a7ff6ff32c.PNG)

**Comment by kknee** [comment]
Change name of OTPS to "Predicted Tides @ lat/lon of station/buoy"

**Comment by kknee** [comment]
this is done on dev:

![image](https://cloud.githubusercontent.com/assets/196868/26499229/d2ff4df6-41ff-11e7-883a-e5322781b864.png)

**Comment by kbailey-noaa** [comment]
@kknee I can't find my notes on this. I know I asked for it to be changed because OTPS isn't a layer with abstract info that a user can read.  So I was trying to make it more user-friendly but now that I see it it still seems confusing.  I know if you drop a virtual buoy, then the predicted tide is returned for that location.  I think that works by sending a lat/long to the software (?), and the prediction is generated based on that single position?  i.e. this has nothing to do with the activated layer (in this case HYCOM Navy), right?  I'm struggling with how to convey to the user what this "layer" is or where it comes from.

Also, I'm concerned we're mixing datums.  The OFS layers are above MLLW but I think Predicted Tides is above MSL.  I'm thinking we should prevent this layer from showing up if an OFS layer is activated.  

Let's hold off on implementing for now.

**Comment by kknee** [comment]
ok, will hold off on pushing to production pending further discussion.  
the predictions are above MSL - we had a long discussion about that at one point, but basically it would be difficult to change because it's a global model.

**Comment by kbailey-noaa** [comment]
Got it. I don't think we should make any change to convert predictions (they are fine above MSL), just recommend we prevent them from appearing if an OFS layer is activated.  I think that would resolve any concerns about mixing datums.

**Comment by kbailey-noaa** [comment]
@kknee I see this in production but not dev.  I turned on global hycom water levels in dev and couldn't find any predictions.

**Comment by Bobfrat** [comment]
@kbailey-noaa It's working for me on dev. Data table is in the lower left hand corner and plot has predicted and hycom tides.
<img width="1437" alt="screen shot 2018-04-18 at 4 53 47 pm" src="https://user-images.githubusercontent.com/5702672/38957642-2249e012-4329-11e8-9858-86bcd4ac277c.png">

**Comment by kbailey-noaa** [comment]
I really need to capture images so you all don't think i'm going crazy.
I see it now too, thanks!
