### ISSUE TITLE
Validate Tool:  Parameter list

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#56]
In http://dev.oceansmap.com/eds/#:

Water temperature, salinity are missing from the list.

Confusing that we label as "water level" in the TOC layer list, but "water elevation" in the parameter list.  Change to water level.

**Comment by gitchrisadams** [comment]
Added Salinity and Water temperature and deployed to dev.
![image](https://user-images.githubusercontent.com/9978238/31838720-128d2bd0-b5ac-11e7-9268-2b2f0267282f.png)

**Comment by kknee** [comment]
@kbailey-noaa this is on production already, closing
