### ISSUE TITLE
Validate tool: selecting a station/model

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#57]
http://dev.oceansmap.com/eds/#:

Should include language somewhere that this is restricted to a comparison of 2 stations, like we do for the multi-station option in the Explore tool.

Once I've selected stations and looked at plots, there doesn't appear to be a way to 'start over,' to allow me to erase and try a new comparison.

**Comment by kknee** [comment]
1. Added requested language to tool overview:

![image](https://cloud.githubusercontent.com/assets/196868/25978488/6180ef88-3690-11e7-8ca8-b5858fc3e814.png)

2. As discussed - the tool updates on the fly, so simply changing any input will kickoff a new comparison

**Comment by kbailey-noaa** [comment]
Looks good.
