### ISSUE TITLE
Validate tool:  Plots

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#58]
Need some type of explanation/description of the error stats table.  

I assume R2 is supposed to be r-squared.  Can we make the 2 a superscript?

**Comment by kknee** [comment]
1. added info button to table, which loads:

![image](https://cloud.githubusercontent.com/assets/196868/25978552/d75ea0ce-3690-11e7-9e24-b1f45ee6ffe0.png)

2. Done

**Comment by kbailey-noaa** [comment]
Looks good!
