### ISSUE TITLE
Missing bounding box

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#60]
West Coast WW3 Wave layer is missing the bounding box

**Comment by kknee** [comment]
@kbailey-noaa it's there, it's just a big AOI so you have to zoom out:

![image](https://cloud.githubusercontent.com/assets/196868/24522146/9fb0a0be-155c-11e7-90f9-b8fa664a4f18.png)

**Comment by kbailey-noaa** [comment]
Weird, I don't see that box and I'm zoomed out farther than the images you sent shows.

![screen shot 2017-03-31 at 4 03 08 pm](https://cloud.githubusercontent.com/assets/11823385/24567437/b2f40e3e-162b-11e7-9ea4-df24943b113b.png)

Also, the directions are gray/black, though the height and period plot fine.  
I'm using chrome, if that helps.

**Comment by kknee** [comment]
I checked production for the bbox issue, it's fine there but I don't see it on dev, so I assume that's where you're looking.  

That wave direction symbology is standard for EDS

**Comment by kbailey-noaa** [comment]
Ah ok.  No, I was looking at prod.  I'm on my mac at home.  I'll check at work again but I first noticed it on my work laptop (windows).

**Comment by kknee** [comment]
Ok, I figured out why we're seeing two different behaviors.  If you use the 'zoom to' tool to go the layer extent the bbox displays.  If you zoom out manually it does not.  We'll investigate.

**Comment by Bobfrat** [comment]
@kbailey-noaa this should be fixed now.
