### ISSUE TITLE
Change location of TDS?

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#61]
For our viewer, is it possible to change the 'location' of the THREDDS server from data.oceansmap.com to eds.ioos.us?
e.g. change from http://data.oceansmap.com/thredds/catalog/EDS/HYCOM_GLOBAL_WMS/catalog.html
to
http://**eds.ioos.us**/thredds/catalog/EDS/HYCOM_GLOBAL_WMS/catalog.html

**Comment by kbailey-noaa** [comment]
@kknee is this possible?

**Comment by kknee** [comment]
@kbailey-noaa looking at options here.  The issue is that the OceansMap TDS is not used only by IOOS.

we could maybe setup a 2nd TDS that references the original OceansMap TDS.

**Comment by kknee** [comment]
@kbailey-noaa see comment above - is this the direction we should go?

**Comment by kknee** [comment]
all set: https://eds.ioos.us/thredds/catalog.html

**Comment by kbailey-noaa** [comment]
@kknee The links in the layers' abstracts for "EDS THREDDS" still point to http://data.oceansmap.com/thredds/.  Can you change these to point to https://eds.ioos.us/thredds/?

**Comment by Bobfrat** [comment]
All set now on dev and production
