### ISSUE TITLE
Change Data Access display

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#63]
We need to at least provide links to the standard services - THREDDS, ERDDAP, SOS, where possible, in all cases.  
This changes the nature of how we display the "data access" link in that information box. Instead of just the one link called "data access" can we provide multiple links named after the service? e.g. "ERDDAP", "SOS", "API" etc.

**Comment by kknee** [comment]
not on dev yet, but here's a teaser of what it will look like:

![image](https://cloud.githubusercontent.com/assets/196868/26083717/54a4d294-39a5-11e7-8568-93b95ef9816d.png)

**Comment by kknee** [comment]
@kbailey-noaa this is ready for review on dev.  I believe the only source we have multiple data access links for is CO-OPS, but we can easily add to other sources now as they come up

**Comment by kbailey-noaa** [comment]
Looks good.  So for those layers with a single source (THREDDS) we'd just display "THREDDS" right?  To be consistent.

**Comment by kknee** [comment]
@kbailey-noaa some of them just go to websites, like NERRS.  What would you want to do in that situation?  'Data provider website'?  I kind of like the generic data access when there is only one.

**Comment by kbailey-noaa** [comment]
How do you grab the NERRS data?  I can't recall if it's via NDBC or NERRS?  Either way NERRS has a web services page that seems more appropriate to point to: http://cdmo.baruch.sc.edu/webservices.cfm 
It looks like SOAP, not SOS, though.

**Comment by kbailey-noaa** [comment]
@kknee I was thinking about this more.  We have 2 potential THREDDS sources - the EDS thredds and the source thredds.  Can we provide both in that data access list?  Just call them "EDS THREDDS" and "Source THREDDS."  Ideally the EDS thredds would be better... e.g. daily files could be aggregated (I realize this might take effort though).

**Comment by kbailey-noaa** [comment]
@Bobfrat - So for CBOFS, the source thredds would be https://opendap.co-ops.nos.noaa.gov/thredds/catalog.html (and that same link would actually be used for all the OFS layers).   i.e. wherever the EDS actually harvests from.  If it isn't THREDDS in all cases, then maybe include "source API" or "source SOS."

**Comment by Bobfrat** [comment]
@kbailey-noaa we have this up on the dev site if you'd like to check it out.

http://dev.oceansmap.com/eds/#

**Comment by kbailey-noaa** [comment]
Great!! Looks good.

**Comment by Bobfrat** [comment]
ok i'll push that up to production site
