### ISSUE TITLE
Ingest WCOFS data as test case

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#66]
CO-OPS will provide a few cycles of WCOFS output on their FTP server.  Once this becomes available please ingest into EDS and only display in the dev oceansmap.

**Comment by kknee** [comment]
@kbailey-noaa we discussed this a while back, but there were no issues with the test.  Any idea on timeframe this data being available more regularly?

**Comment by kbailey-noaa** [comment]
No, not sure.  The need for availability of the non-operational netCDF files (so that we/ASA can harvest for testing purposes) was raised by CO-OPS internally, but a week later their IT Chief left!  Hoping CO-OPS can publish some type of dev TDS for test purposes so we can harvest from there.  But I think the file size is a problem.

**Comment by kbailey-noaa** [comment]
@kknee WCOFS is available on CO-OPS THREDDS server.  I wanted to resurrect this issue and get these data into the EDS Viewer under the "In Development" category.  Please consider this high priority.
@BeckyBaltes looping you in for awareness.

**Comment by kknee** [comment]
ok, we'll take a look asap

**Comment by kknee** [comment]
Name = NOAA West Coast (WCOFS) ?

What do you want to use for an abstract?

**Comment by kbailey-noaa** [comment]
@kknee yes re: the name.
Abstract:
"Notice: The WCOFS outputs are currently under evaluation. Please do not attempt to use the outputs operationally for navigation and/or recreation purposes.
A three-dimensional U.S. West Coast Operational Forecast System (WCOFS) was developed in a joint project of the NOAA/National Ocean Service (NOS)/Office of Coast Survey, the NOAA/NOS/Center for Operational Oceanographic Products and Services (CO-OPS), and the NOAA/National Weather Service (NWS)/National Centers for Environmental Prediction (NCEP) Central Operations (NCO) using Rutgers University's Regional Ocean Modeling System (ROMS). WCOFS generates water level, current, temperature and salinity nowcast and forecast guidance four times per day for wind, water level, currents, temperature, and salinity. 
For more detailed information about WCOFS, please click [here](https://tidesandcurrents.noaa.gov/ofs/dev/wcofs/wcofs_info.html)."

**Comment by kbailey-noaa** [comment]
@kknee To recap, we agreed to add WCOFS to the gold standard THREDDS, but we don't need WCOFS in EDS.  It would be good to show in OceansMap a timeframe - a period of 5-7 days - of data for future user assessments.  Ideally we'd be able to have a continuously updating visualization but the WCOFS files are inconsistent/troublesome, so this isn't possible.

**Comment by kknee** [comment]
@kbailey-noaa  - WCOFS is here: http://tds.eds.ioos.us/thredds/catalog/ioos/ioos-ofs-wcofs.html (going back to 20 April).  Do you want us to keep bringing it in for now?

**Comment by kbailey-noaa** [comment]
@kknee @Bobfrat  If it isn't too much load, then yes.  If it's a heavy dataset that is costly, then no.  Also, what is the status of displaying it in the IOOS Model Viewer (In Development category)? Per above comment, does not need to be continuously updated - I just want the ability to show something to OCS, whether it's a specific week for which we have data or whether it's continuously updating.  Either or.

**Comment by kbailey-noaa** [comment]
Closing because WCOFS data are in the tds.eds.ioos.us (per May 13 comment) and can see a 'preview' of the data as well.
