### ISSUE TITLE
CBIBS stations missing

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#67]
If I select the CBIBS layer (both EDS production and dev) the stations do not show up.  I checked the CBIBS website and the data are displaying.

**Comment by kknee** [comment]
Access to CBIBS API has been turned off.  Working with NCBO to restore our access to the API on an NCBO server.

**Comment by kbailey-noaa** [comment]
@kknee Can we just grab these via NDBC?

**Comment by kbailey-noaa** [comment]
Stations are there but not showing all the data.  Data are fully available via CBIBS website but not NDBC's website (I realize NDBC is the EDS source, and this lack of data is an NDBC problem).  Would be ideal to grab data from CBIBS, not NDBC.  If not possible, pls lmk.

**Comment by kknee** [comment]
@kbailey-noaa we're harvesting the data directly from CBIBS now, will add to the model viewer next

**Comment by kknee** [comment]
@kbailey-noaa these are on dev.  still testing here, but feel free to take a look.

**Comment by kbailey-noaa** [comment]
Nice!  We should probably change the name from CBIBS Buoys to Chesapeake Bay buoys to be consistent.

**Comment by kknee** [comment]
no problem on the name change, but do you really think people are going to like these generic obs layer names?  I'm finding it hard to use now, but I was so used to the old names:

![image](https://user-images.githubusercontent.com/196868/38908544-c8a43606-428e-11e8-8d40-dbde71575738.png)

**Comment by kbailey-noaa** [comment]
I'm inclined to agree....I'm not loving it.

The problem is attribution, particularly for the other obs layers.  Our attribution survey revealed that the RAs don't like CDIP in the IOOS Model Viewer TOC - one person recommended the data layer name should be a variable (e.g. waves) without the institution and then the station pop-up has a link to the full attribution.  (But I think we're finding it's TOO generic).  Another found it confusing because we show one owner/operator in the TOC and then another owner/operator in the pop-up (I agree..).

BTW are we losing that attribution in the dev version with the loss of the pop-up?  I couldn't tell in dev - none of the obs layers worked.

In IOOS we're refining attribution requirements for our various products. We're considering a link to an 'attribution page' within each product that shows all available attributes gathered from the source metadata.  For the Model Viewer this could be another icon next to the layer name for "metadata" or a link to a metadata webpage within the abstract that lists attribution (institution, funder, etc).  

Anyway, another option for obs layer names:
- NOAA CBIBS buoys
- NOAA NDBC partner current profiling stations
- NOAA NERRS estuarine stations
- NOAA NDBC & partner weather buoys/stations
- Maryland DNR ecosystem stations
- NOAA CO-OPS water level stations
- USACE & partner wave buoys

It's hard because we want to promote IOOS RAs and yet all the data are harvested from data brokers/national platforms that harvest from myriad partners.  Maybe in the future we could harvest RA obs from the Axiom sensor map (they're setting up an ERRDAP) and show as another layer named "IOOS buoys/stations" or something.

**Comment by kknee** [comment]
@kbailey-noaa 

1. I like the updated list of layer names above, go with those?
2. not sure about obs layer not working, do you have an example?  maybe you caught us during a dev site update
3. attribution is the same as in the pop-ups, but CBIBS looks like it needs to be updated for consistency,
4. regarding specific situations like CDIP vs. something else in the TOC - CDIP was added as a separate layer specifically because of user feedback in the past.  Not sure hwo to make everyone happy here.  I think the updated layer list names above are a good start.

**Comment by kbailey-noaa** [comment]
@kknee Could've sworn I responded to this...I think we already discussed on the phone but for documentation purposes:
1. Yes
2. Nope, and it's working now! 
3. Roger that
4. Right...  Someone will always complain.  Let's see what feedback I get with this updated list.

**Comment by kbailey-noaa** [comment]
This issue looks like it was resolved, therefore closing.
