### ISSUE TITLE
Addition of new models - Decision process

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#69]
(As described in the SOW):
Determine a decision process to determine which models can be integrated into the EDS, and the priority thereof.  
https://docs.google.com/spreadsheets/d/1A-FEFgcQavnwEQ8nl4RXgd6BC9xWd5FdLqFb-agNN7s/edit#gid=642717348

**Comment by kknee** [comment]
@kbailey-noaa our decision process in the last year was pretty informal - basically added new models on request as long as the addition was feasible.  As we didn't have too many requests this worked.  

A more formal process would be a balance between strategic importance and level of effort.  With LOE depending on factors such as data format, data availability, parameters, file size etc.

**Comment by kbailey-noaa** [comment]
Moved to Trello - https://trello.com/c/dwsee3F9/13-add-ra-models-to-the-eds
