### ISSUE TITLE
Add ability to save a session

### ISSUE THREAD

**Issue by kknee** [asascience-open/IOOS-EDS#7]

**Comment by kknee** [comment]
further description from @lukecampbell "As a data consumer and map user, it would be nice to create permanent links to a map configuration so that I can create a story and share it with other users and curious citizens"

**Comment by kknee** [comment]
The ability to create a permalink is now on dev:

![image](https://user-images.githubusercontent.com/196868/42818539-2152e822-899f-11e8-9c59-628a6512ba41.png)

![image](https://user-images.githubusercontent.com/196868/42818543-277619ae-899f-11e8-8bc2-8f0ccf922268.png)

**Comment by kbailey-noaa** [comment]
Looks good.
