### ISSUE TITLE
Investigate mobile friendly interface

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#70]
(As described in the SOW):
Determine if there is a way to make the EDS Model Viewer mobile-friendly, meaning displays are not distorted and can be used on a mobile device.  This does not need to be a separate app, which is likely time-consuming and expensive.

**Comment by kbailey-noaa** [comment]
@kknee this was discussed and I believe we tabled it, but if you have notes on that decision can you please include?

**Comment by kknee** [comment]
@kbailey-noaa yes, we tabled that conversation as we didn't want to eat up the entire budget dealing with mobile issues

**Comment by kbailey-noaa** [comment]
@kknee This appears to be part of the MARACOOS / UDel OTT proposal.  Would making the CO-OPS front-end mobile friendly also benefit the IOOS Model Viewer?

**Comment by kbailey-noaa** [comment]
@kknee Wow, missed this comment from a year ago.  Closing, given that the CO-OPS instance may resolve this.
