### ISSUE TITLE
Remove NDBC buoys from default display

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#72]
I'm learning that showing observations in a product targeted towards model displays is confusing.  RAs see this and wonder why their observations aren't shown.  Pls remove NDBC buoys as a default active layer.

**Comment by kknee** [comment]
complete on dev: 
![image](https://cloud.githubusercontent.com/assets/196868/25751120/eb139804-3181-11e7-80fe-72b6b4fcf32f.png)
