### ISSUE TITLE
Add RA Name to Model Name

### ISSUE THREAD

**Issue by kknee** [asascience-open/IOOS-EDS#75]

**Comment by kknee** [comment]
and add 'NOAA' before OFS model names

**Comment by kbailey-noaa** [comment]
Add RA name before the model name.

**Comment by kknee** [comment]
@kbailey-noaa here's my list of changes, let me know if you have an edits:

Chesapeake Bay 3D (CBOFS) = NOAA Chesapeake Bay 3D (CBOFS)
Columbia River (CREOFS) = NOAA Columbia River (CREOFS)
Delaware Bay 3D (DBOFS) = NOAA Delaware Bay 3D (DBOFS)
East Coast (PE Shelf) = MARACOOS East Coast (PE Shelf)
Great Lakes (LEOFS) = NOAA Great Lakes (LEOFS)
Great Lakes 3D (LHOFS) = NOAA Great Lakes 3D (LHOFS)
Great Lakes 3D (LMOFS) = NOAA Great Lakes 3D (LMOFS)
Great Lakes 3D (LOOFS) = NOAA Great Lakes 3D (LOOFS)
Great Lakes 3D (LSOFS) = NOAA Great Lakes 3D (LSOFS) 
Gulf of Maine (FVCOM) = NERACOOS Gulf of Maine (FVCOM) 
Gulf of Mexico (NEGOFS) = NOAA Gulf of Mexico (NEGOFS)
Gulf of Mexico (NGOFS) = NOAA Gulf of Mexico (NGOFS) 
Gulf of Mexico (NWGOFS) = NOAA Gulf of Mexico (NWGOFS) 
Hawaii (ROMS) = PACIOOS Hawaii (ROMS)
Massachusetts Bay (FVCOM) = NERACOOS Massachusetts Bay (FVCOM) 
Mid Atlantic (Espresso ROMS) = MARACOOS Mid Atlantic (Espresso ROMS)
New York (NYHOPS) = MARACOOS New York (NYHOPS) 
New York 3D (NYOFS) = NOAA New York 3D (NYOFS)
San Francisco (SFBOFS) = NOAA San Francisco (SFBOFS) 
St Johns River 3D (SJROFS) = NOAA St Johns River 3D (SJROFS) 
Tampa Bay 3D (TBOFS) = NOAA Tampa Bay 3D (TBOFS)
West Coast (OSU ROMS) = NANOOS West Coast (OSU ROMS) 
Atlantic (ESTOFS Surge Tide) = NOAA Atlantic (ESTOFS Surge Tide)
Chesapeake Bay (CBOFS) = NOAA Chesapeake Bay (CBOFS)
Delaware Bay (DBOFS) = NOAA Delaware Bay (DBOFS) 
Great Lakes (LHOFS) = NOAA Great Lakes (LHOFS)
Great Lakes (LMOFS) = NOAA Great Lakes (LMOFS)
Great Lakes (LOOFS) = NOAA Great Lakes (LOOFS) 
Great Lakes (LSOFS) = NOAA Great Lakes (LSOFS) 
New York (NYOFS) = NOAA New York (NYOFS)
St Johns River (SJROFS) = NOAA St Johns River (SJROFS)
Tampa Bay (TBOFS) = NOAA Tampa Bay (TBOFS)
Gulf of Maine (FVCOM Bottom Water Temp) = NERACOOS Gulf of Maine (FVCOM Bottom Water Temp)
Gulf of Maine (FVCOM Surface Temperature) = NERACOOS Gulf of Maine (FVCOM Surface Temperature)
Caribbean (SWAN Direction) =  CariCOOS Caribbean (SWAN Direction)
Caribbean (SWAN Height) = CariCOOS Caribbean (SWAN Height) 
Caribbean (SWAN Period) = CariCOOS Caribbean (SWAN Period)
NWPS TBW Wave Direction = Tampa Bay (NWPS Wave Direction)
NWPS TBW Wave Height = Tampa Bay (NWPS Wave Height)
NWPS TBW Wave Period = Tampa Bay (NWPS Wave Height)
CARIB_WRF = CariCOOS Caribbean (CARIB_WRF)
CARIB_WRF_2KM = CariCOOS Caribbean (CARIB_WRF_2km)
Mid-Atlantic (Rutgers WRF 3km) = MARICOOS Mid-Atlantic (Rutgers WRF 3km)
Mid-Atlantic (Rutgers WRF 9km) = MARICOOS Mid-Atlantic (Rutgers WRF 9km)
NWPS TBW Winds = NOAA Tampa Bay (NWPS TBW)

**Comment by kknee** [comment]
@kbailey-noaa does the list above look okay to you?

**Comment by kbailey-noaa** [comment]
I learned CariCOOS made their acronym all caps this month so it's now CARICOOS.  Also looks like MARACOOS is spelled wrong for 43 and 44 (haha).  And PACIOOS is actually PacIOOS.

But to address your real question: 38 - 40 should be NOAA.  The rest looks good.

**Comment by kbailey-noaa** [comment]
We should also rename the HF Radar observations with the RA name in front of it.  I reached out to Jack Harlan for help on suggested layer renaming.

**Comment by kknee** [comment]
here's the consensus from @kbailey-noaa and Jack Harlan:

Caribbean (HF Radar PRVI) = CARICOOS HF Radar (PRVI)
Hawaii (HF RADAR USHI) = PacIOOS HF Radar (USHI)
Mid Atlantic (HF Radar MARACOOS) = MARACOOS Mid Atlantic HF Radar

**Comment by kknee** [comment]
all layer name updates have been pushed:

![image](https://cloud.githubusercontent.com/assets/196868/26005542/61abc614-3707-11e7-9e5d-b601ba2f3d9e.png)

**Comment by kbailey-noaa** [comment]
Looks good! Please implement.
