### ISSUE TITLE
GoMOFS data ingest for testing

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#76]
CO-OPS has released GoMOFS data for user testing/validation through their site.  Looking to see if we can get the data as well as a trial run (i.e. show CO-OPS what we could do to facilitate this test process).  Some details also below, because we also need to ingest this new dataset once it becomes operational.  This issue only relates to the test phase, and I'll create a new issue for once it becomes operational.
Included in milestone 1.2 because of the time sensitivity, but also depends on AJ/CO-OPS supplying data.

From CO-OPS:
Gulf of Maine Operational Forecast System (GoMOFS) is going to be transitioned in June of 2017 to parallel (pre-production) on NOAA's Weather Climate Operational Supercomputing System (WCOSS).  Before NCEP’S parallel, CO-OPS will conduct a 30 day real-time evaluation process for GoMOFS from May 1 to May 30 which is officially required. 
 
GoMOFS is now running 4 cycles a day by CO-OPS at 00Z, 06Z, 12Z and 18Z with 72 hours forecast for each cycle.  The model output and details of the model can be found on the following website
 
https://tidesandcurrents.noaa.gov/ofs/dev/gomofs/gomofs.html
 
During this 30-day evaluation period, model output related links will not work properly on the website.  The model archived graphics link, OPenDAP and THREDDS will start incorporating GoMOFS output data after NCEP’s parallel test.
 
We need to have a formal evaluation, based on feedback from users, to present to NCEP management at an appropriate time before GoMOFS is transitioned to pre-production. Your comments and feedback about GoMOFS model outputs and web products are very important and greatly appreciated. Please let us know whether you would like to be a GoMOFS evaluator and please feel free to forward this message to anyone who you think may be interested in GoMOFS evaluation.

**Comment by kknee** [comment]
@kbailey-noaa it doesn't sound like there is anything we can get started on yet - can you confirm?  I don't see the files on the CO-OPS TDS.

**Comment by kknee** [comment]
Sample data received 5/3, EDS team is reviewing level of effort for integration

**Comment by kknee** [comment]
@kbailey-noaa sample data has been reviewed by the EDS team and successfully integrated on the development instance of EDS.  Because it's not a live feed we have not enabled it on production EDS or in OceansMap.  Any word on when a live feed will be available? How do you want to handle this issue as part of Milestone 1.2 if the feed will not be available soon?

**Comment by kbailey-noaa** [comment]
Hi,
If it's ingested and available on the dev Oceansmap then the task is complete. This github issue was more about ability to view and demonstrate to CO-OPS use of EDS as an assessment tool during model validation/testing. 

It should be operational at CO-OPS by the end of the FY. I will put in another github issue for ingesting the operational data and displaying in prod oceansmap but that's for a distant milestone. 

K

**Comment by kknee** [comment]
one more question...this data is 3D, so assuming you want us to include this as a 3D layer similar to CBOFS?

**Comment by kbailey-noaa** [comment]
Correct.

**Comment by kknee** [comment]
3D Currents, Salinity, and Water Temp added for the demo files (must change timeslider to 4/26 after 04:00 to view:

![image](https://cloud.githubusercontent.com/assets/196868/26024453/68c130c2-379f-11e7-80c6-097292456c12.png)

**Comment by kbailey-noaa** [comment]
Can we take these layers out of the production version?  Need to do this asap - before I can announce changes.  I don't want people seeing that and thinking GoMOFS is operational.

**Comment by kknee** [comment]
Sure - at the moment it will have to come out of both production and dev as IOOS only has a single EDS account/key.  We'll pull from both and I'll also see about splitting out the EDS keys for the dev and production viewers

**Comment by kknee** [comment]
removed from the EDS Viewer data catalog.  I'll start a separate issue for spilling out the keys.
