### ISSUE TITLE
TBOFS and CBOFS Channel animations don't change

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#80]
The animation shows no change in the variable plots.  But the graphics animate, and the timestamp changes.

**Comment by kknee** [comment]
these are fixed

**Comment by kbailey-noaa** [comment]
This is still an issue.  Plots aren't changing with time.

**Comment by kbailey-noaa** [comment]
Also, the timestamps don't match what the CO-OPS page shows.  https://tidesandcurrents.noaa.gov/ofs/tbofs/tbofs_mcf.html
The time/zone dropdown menu on the CO-OPS page shows the same time range as the EDS Viewer (in this case, 8/7 0900 to 8/8 0900) but CO-OPS times are labeled EDT and EDS Viewer labels are Z.  Please confirm the time zone labels.

**Comment by kbailey-noaa** [comment]
The plots animate, but time zone still need to be resolved.

**Comment by Bobfrat** [comment]
Time zone has been updated to Eastern
