### ISSUE TITLE
West Coast STPS troubles

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#83]
The STPS west coast layer loads, but when I drop a virtual buoy I get "no results" in the pop up, despite vectors on the map.  I even zoomed in to drop a buoy right on a vector but no data.

**Comment by kknee** [comment]
This is fixed, @kbailey-noaa please test on your end and close if working for you too

**Comment by kbailey-noaa** [comment]
Just tested it and it works.
