### ISSUE TITLE
OFS Water level layers missing 3D

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#84]
I could have sworn we had depth options for the water level OFS layers?

**Comment by kknee** [comment]
water level doesn't vary with depth, just with time & space :

![image](https://cloud.githubusercontent.com/assets/196868/26748768/c6c31e26-47ce-11e7-91f1-f33b4c621753.png)

**Comment by kbailey-noaa** [comment]
omg haha yes.  Brain fart.
