### ISSUE TITLE
Add variables to MARACOOS Mid-Atlantic Espresso ROMS

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#86]
The Espresso ROMS only has surface currents available in the model viewer.  Please add water temp and salinity.  Thinking about adding sea surface height but this is up for discussion.  Will log another github issue as a placeholder...

**Comment by kbailey-noaa** [comment]
I think it's one of these:
https://data.ioos.us/organization/edb576db-0b8f-4ebb-bb69-3f9bd8324f4c?res_format=WMS

**Comment by kknee** [comment]
@kbailey-noaa received word two weeks ago that ESPRESSO is being replaced with DOPPIO.  We are already working on that integration into EDS. Closing this issue in favor of a new one to complete the replacement in OceansMap
