### ISSUE TITLE
The 'there was a problem drawing this layer' error message is misleading

### ISSUE THREAD

**Issue by mwengren** [asascience-open/IOOS-EDS#88]
When a user clicks to enable display of a model that is outside of the current map window, a more informative error message should be used if possible.  

'There was a problem drawing this layer' sounds as though the data is unavailable, or some other error is preventing the model from being shown, rather than just being outside the viewing area.

**Comment by kknee** [comment]
@mwengren we're aware of this issue, but requires additional feedback from the EDS side of things for us to be able to differentiate whether the data is unavailable vs just outside the map area.  Unfortunately, not a simple update...

**Comment by mwengren** [comment]
Thanks, we noticed this in the DMAC meeting last week and weren't aware it was a prior known issue.  I had noticed it before but had only tested a few models and assumed it was a temporary data issue with those models.

**Comment by kbailey-noaa** [comment]
This issue is resolved.  If I activate a layer outside the current map view I don't get an error anymore.
