### ISSUE TITLE
Active Tropical Cyclones layer isn't loading

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#89]
It doesn't work in either production or dev.  I only get the spinning wheel.

**Comment by kknee** [comment]
because ESRI took down that service.  We just realized that ourselves and added an alternate one to the data catalog, but hasn't been pushed yet.

**Comment by mwengren** [comment]
Let me put in my plug for the nowCOAST tropical cyclones service: 

https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/wwa_meteocean_tropicalcyclones_trackintensityfcsts_time/MapServer

They just redid their symbology so it is much improved, and it is 24 x 7 supported and won't be discontinued any time soon (:thumbsdown: Esri)

**Comment by Bobfrat** [comment]
@kbailey-noaa should be working now.

**Comment by kbailey-noaa** [comment]
Confirmed.
