### ISSUE TITLE
Allow plots (TS and profile) from multiple virtual buoys

### ISSUE THREAD

**Issue by kknee** [asascience-open/IOOS-EDS#91]
from Gregory Dusek:

It might be neat to have the option to plot the 3d profiles from several virtual buoys at the same time - same with the time series for that matter, unless maybe there is a way to do this already?

**Comment by kbailey-noaa** [comment]
We can do this by adding virtual buoys to the map.  Won't show profiles at the same time, but I haven't heard this come back as a priority upgrade.
