### ISSUE TITLE
Several PacIOOS stations missing

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#92]
Looking at Honolulu, the available stations in the EDS Viewer don't match what shows up on the NDBC map.  Several PacIOOS stations are missing.
There is only 1 station in the EDS Viewer (top) vs at least 8 in the NDBC map (bottom):

![honolulu_eds](https://user-images.githubusercontent.com/11823385/27546208-2314dea0-5a60-11e7-9072-c42959a76f35.PNG)

![honolulu_ndbc](https://user-images.githubusercontent.com/11823385/27546207-230e7ad8-5a60-11e7-93ab-062c11b77d16.PNG)

**Comment by kbailey-noaa** [comment]
Update: I realized the missing stations are under "CDIP" not NDBC & Partner stations.  So I suppose the question is why is that one station not under CDIP?  51211 Pearl Harbor Entrance.

**Comment by Bobfrat** [comment]
@kbailey-noaa should be all set now

<img width="1432" alt="screen shot 2017-09-12 at 1 56 37 pm" src="https://user-images.githubusercontent.com/5702672/30340955-4954e69c-97c2-11e7-9b63-321cf92ac591.png">
