### ISSUE TITLE
Alaska CO-OPS stations missing

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#93]
A user (James Clontz, CO-OPS) pointed out that many CO-OPS stations in Alaska are missing from the EDS viewer.  I confirmed there are a few coastal stations north of Anchorage missing.

**Comment by Bobfrat** [comment]
@kbailey-noaa We found that the following stations were missing and were added:
9468333, 9468756, 9491094 and 9497645

Are we missing any others?

**Comment by kbailey-noaa** [comment]
That's it!  Thanks.
