### ISSUE TITLE
Getting back to map from "explore page" isn't obvious

### ISSUE THREAD

**Issue by dpsnowden** [asascience-open/IOOS-EDS#94]
I was looking at a CDIP buoy as in the map below.  I clicked the explore link at the bottom right of the balloon and went to the explore graphs page.  It wasn't obvious how to get back to the map.  Eventually I clicked the map button again and found my way back to the map.  Consider making it a little more obvious if possible.  

`Return to map` button at the top of the graphing sub-window perhaps?

![image](https://user-images.githubusercontent.com/3603125/28470670-6be4f294-6e08-11e7-9ace-1c89a1d6a456.png)

**Comment by gitchrisadams** [comment]
@dpsnowden What do you think about just changing the text on the button to "Back to Map". See screenshot. Probably without the arrow, just the text/button. 

![backlink](https://user-images.githubusercontent.com/9978238/30665641-a2d486a6-9e1f-11e7-96f3-fcfb0fb609ab.png)

**Comment by kbailey-noaa** [comment]
@gitchrisadams I'll speak for Derrick on this - I think that change looks good and is more obvious.
