### ISSUE TITLE
Rename HFR MAR layers

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#96]
I assume this is a MARACOOS product?  If correct, please rename to MARACOOS HF Radar 1km and 2km respectively (should make the 1km and 2km consistent with the UCSD HFR layer naming convention so we don't have a mix of caps and noncaps, etc.).
Is the MARACOOS HF Radar layer no longer working?  Actually, I can't get any of these MARACOOS HFR layers to load...

**Comment by Bobfrat** [comment]
@kbailey-noaa layers have been renamed
