### ISSUE TITLE
Alaska NDFD issue

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#97]
From a user:
Alaska NDFD appears to have an issue displaying. I see wind barbs but they don't see to be correct and the BBOX doesn't cover AK at all (see attached screenshot).
![selection_299](https://user-images.githubusercontent.com/11823385/28944225-c179e9a0-786f-11e7-9855-d8541893f34e.png)

It should look something like this:
http://portal.aoos.org/#module-metadata/b5285b17-0993-478c-95bc-756964fbfcf8/1d77239e-7f48-4fdd-bf39-e317fac5bf3b

**Comment by Bobfrat** [comment]
Update from EDS team: 
"Moved this from the current sprint, to our next sprint. We are going to have to take a much closer look at the grib2 files we are acquiring from the source."

**Comment by kbailey-noaa** [comment]
Alaska NDFD is now missing from the Viewer.

**Comment by kbailey-noaa** [comment]
@kknee I don't know that we necessarily require Alaska NDFD (haven't heard anyone complain).  Did ASA remove it from the Viewer for a particular reason?  I'm wondering if I should just close this issue.
