### ISSUE TITLE
Expand TBOFS/CBOFS Channel forecasts

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#98]
CO-OPS went live with the [TBOFS channel forecast](https://tidesandcurrents.noaa.gov/ofs/tbofs/tbofs_mcf.html). They are looking to scope out a plan in FY18 to expand this product and are looking for ways to work with IOOS and leverage what we've done with the EDS Model Viewer channel forecasts.

We need to expand this product to at least show what CO-OPS already shows - it should mimic what is shown on their [TBOFS channel forecast site](https://tidesandcurrents.noaa.gov/ofs/tbofs/tbofs_mcf.html).  At this point, we need to add currents, precipitation, and visibility.

**Comment by Bobfrat** [comment]
@kbailey-noaa We won't have the ability to scroll in the animation so I will play around with shrinking the axes of the plots and increasing the image height to try to fit all the plots in. I can combine wind speed and direction into 1 plot so that will help.

**Comment by kbailey-noaa** [comment]
Closing - when CO-OPS gets their OceansMap instance they can expand if they choose.
