### ISSUE TITLE
Channel forecast labels/displays

### ISSUE THREAD

**Issue by kbailey-noaa** [asascience-open/IOOS-EDS#99]
Please change the units in the plots - they are inconsistent (knots and meters).  Please change them all to english units - knots, feet, etc.   

Also, change the plot labeling to match the CO-OPS displays (https://tidesandcurrents.noaa.gov/ofs/tbofs/tbofs_mcf.html)
- Water Elevation should be Tampa Bay Along-Channel Forecast / Water Levels (or Currents, etc).   Water elevation y-axis should be "Height (Feet relative to MLLW)

**Comment by Bobfrat** [comment]
@kbailey-noaa I updated the labels, titles, and units. I noticed the elevation forecast data isn't available throughout the animation duration so I'll check on that. I'll also work on adding the new parameters as described in issue https://github.com/asascience-open/IOOS-EDS/issues/98
